"""The Ssarathi Ruins' secrets: what the jade keeps under the silt."""
from secretrooms import Secret

REGION = "ssarathi_ruins"
NAME = "Ssarathi Ruins Secrets"
PALETTE = {"floor": "verdant_mossy_stone", "wall": "verdant_carved_jade", "ceil": "verdant_terrace_stone",
           "rock": "verdant_wet_limestone", "stone": "verdant_terrace_stone", "timber": "timber_dark",
           "water": "water_lagoon", "crystal": "verdant_jade", "node": "verdant_frond", "turf": "verdant_jungle_floor"}
PROP_PALETTE = {"rock": "verdant_wet_limestone", "bark": "bark_dark", "stone": "verdant_terrace_stone",
                "timber": "timber_dark", "dark": "bark_dark"}

SECRETS = [
    Secret("ruins-moss-hollow", "The Scale-Moss Hollow", "grotto", "root_door", "root-arch", (10.0, 8.0),
           resources=(("Ssarathi Scale Moss", 5), ("Grave Moss", 3)),
           note="A hollow under the root arch where the scale moss grows thick and undisturbed."),
    Secret("ruins-lily-garden", "The Lily Court Garden", "garden", "cracked_slab", "lily-court", (10.0, 8.0),
           resources=(("Delta Lotus", 4), ("Cenote Watercress", 4), ("Sunstone Flint", 3), ("Ssarathi Scale Moss", 3)),
           area=("harvest_speed", 2),
           note="The court's sunken garden, kept by the archive's copyists."),
    Secret("ruins-gate-cache", "The Serpent Gate Cache", "cache", "cellar_hatch", "serpent-gate", (10.0, 8.0),
           resources=(("Sunstone Flint", 3), ("Grave Moss", 3)),
           note="The gate-keepers' cellar: chest, bench and flint enough for a siege."),
    Secret("ruins-vault-of-the-sun", "The Sun Vault Undercroft", "vault", "cracked_slab", None, (3.0, 3.0), key="Storage Token",
           door_map="ssarathi_royal_archive", door_space="royal_archive.central_archive",
           texts=(("The lineage", "The archive holds the lineage; the stelae hold the order. What is made under the sun vault is copied into both and counts double."),),
           note="The strongroom under the sun vault."),
    Secret("ruins-hatchery-pit", "The Hatchery Pit", "pen", "loose_stone", "hatchery-descent", (10.0, 8.0),
           creatures=(("delta_mud_crab", 4), ("canopy_glider", 3)),
           note="A brood cell the wardens stock for the young to learn on."),
    Secret("ruins-plaza-school", "The Ritual Plaza School", "school", "cracked_slab", "ritual-plaza", (10.0, 8.0),
           texts=(("Reading", "The plaza's under-room. Books read three times as fast in the jade quiet."),
                  ("The archive", "The royal archive is the room behind the sun vault. It was entered from the steppe once, by mistake, on paper."),
                  ("The falls", "North falls and east falls drain the same cistern. The cistern shaft is the honest way down.")),
           note="Where the copyists learn the lineage."),
    Secret("ruins-falls-spring", "The East Falls Spring", "spring", "loose_stone", "east-falls", (-10.0, 8.0),
           note="Behind the east falls a warm chamber the temple never recorded."),
    Secret("ruins-shrine-butts", "The West Shrine Butts", "range", "cellar_hatch", "west-shrine", (10.0, 8.0),
           creatures=(("swamp_heron", 3),),
           note="A gallery under the west shrine with herons at the far end."),
    Secret("ruins-stela-reliquary", "The Sun Stela Reliquary", "reliquary", "shrine_slab", "sun-stela", (10.0, 8.0), key="Sunstone Flint",
           texts=(("The rebuke", "The ruling under rebuke was written in the archive and read at the stelae. The two copies differ by one name."),
                  ("The verification", "Verification lapsed when the copyist who kept it drowned in the cistern, or left."),
                  ("The tenth", "The tenth mouth of the delta was claimed by the ruins and the claim was never carried down.")),
           note="Opened with sunstone flint, the stela's own fire."),
    Secret("ruins-cistern-well", "The Cistern Well", "nullwell", "drain_grate", "cistern-shaft", (10.0, 8.0),
           creatures=(("saltmarsh_crocodile", 2),),
           note="The cistern's jade drinks every spell; the crocodile penned there does not care."),
    Secret("ruins-temple-focus", "The Great Temple Focus", "focus", "cracked_slab", "great-temple", (-14.0, 8.0), key="Iron Rune",
           note="Under the great temple the ether pools; spells cost half."),
    Secret("ruins-rootrun", "The Root-Run", "tunnel", "root_door", "undercroft-mouth", (10.0, 8.0),
           resources=(("Ssarathi Scale Moss", 3), ("Mangrove Sap", 3)),
           links=(("manymouth_delta", "secret-delta-rootrun-mouth", "Up into the Manymouth Delta"),),
           note="A root-run under the border, out by the delta's great banyan."),
    Secret("ruins-waystone", "The Ruins Waystone", "waystone", "cracked_slab", "channel-bridge", (10.0, 8.0), key="Iron Rune",
           links=(("four_gates_secrets", "gates-waystone", "The Four Gates"),
                  ("verdant_stair_secrets", "stair-waystone", "The Verdant Stair"),
                  ("manymouth_delta_secrets", "delta-waystone", "The Manymouth Delta"),
                  ("crownwater_secrets", "crown-waystone", "Crownwater")),
           note="Four stones under the channel bridge. An iron rune wakes them."),
    Secret("ruins-shrine-eyrie", "The East Shrine Eyrie", "eyrie", "ivy_arch", "east-shrine", (10.0, 8.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Keys", "A secret that asks for an item asks for it in your pack, not in your hand. It is not used up.")),
           note="A pocket over the east shrine."),
    Secret("ruins-culvert-mouth", "The Culvert Mouth", "mouth", "drain_grate", "north-falls", (10.0, 8.0),
           links=(("verdant_stair_secrets", "stair-culvert-far", "Up the culvert to the Verdant Stair"),),
           note="Where the stair's culvert comes out in the ruins."),
]
