extends "res://tests/capture.gd"

func frame_at(id: String, filename: String, camera_zoom := 28.0) -> void:
	go(id)
	scene.player.position = scene.tile_position(Vector2i(q.state.tile[0],q.state.tile[1]))
	scene.zoom = camera_zoom
	scene._refresh()
	scene._update_camera(1)
	await shot(filename)

func _run() -> void:
	output = OS.get_environment("LANTERN_ARTIFACTS")
	if output.is_empty(): output = ProjectSettings.globalize_path("res://artifacts")
	DirAccess.make_dir_recursive_absolute(output)
	root.size = Vector2i(1440,900)
	scene = load("res://main.tscn").instantiate()
	root.add_child(scene)
	await process_frame
	q = scene.q
	q.reset()
	scene.player.position = scene.tile_position(Vector2i(q.state.tile[0],q.state.tile[1]))
	scene._update_camera(1)
	await shot("01-arrival")
	go("nesh")
	go("caldus")
	act("supply")
	await frame_at("caldus","02-boathouse")
	go("chart")
	act("chart")
	act("map")
	await frame_at("reed","03-garden")
	for i in range(3): act("harvest","Reed")
	await frame_at("quartz","04-quartz",22)
	act("harvest","Quartz")
	await frame_at("lower_cache","05-workshop",24)
	act("deposit","Reed",3)
	act("deposit","Quartz")
	act("withdraw","Wood Plank")
	act("withdraw","Cloth Roll")
	act("withdraw","Hatchet")
	act("craft")
	act("equip","Sword")
	act("equip","Shield")
	await frame_at("boar","06-boar",23)
	for i in range(4): q.combat_round()
	go("rest")
	act("eat")
	act("spend","Matter")
	go("upper_cache")
	act("withdraw","Reed",3)
	act("withdraw","Quartz")
	await frame_at("housing","07-beacon-unlit",30)
	act("repair")
	act("light")
	await shot("08-beacon-restored")
	await frame_at("dock","09-return-dock",30)
	act("sell")
	act("buy")
	go("ferry")
	act("depart")
	scene.overview = true
	scene._refresh()
	scene._update_camera(1)
	scene.boat.position = Vector3(110,-.5,-22)
	await shot("10-island-overview")
	print("Art review: %d checks, %d failures." % [checks,failures])
	quit(1 if failures else 0)
