#!/usr/bin/env python3
"""Draw the Eloria action cursor set.

Eternal Lands swaps the hardware pointer to say what a click will do: an eye
over something inspectable, a speech bubble over an NPC, a sword over an enemy,
and so on (thirteen glyphs, listed in the legacy client's cursors.h, plus
Eloria's own grasping hand for an item the click will move).  Eloria keeps
that behaviour but not the legacy artwork: every glyph below is original
pixel art, drawn in the same visual language - white fill, single black
outline, transparent elsewhere - so the pointer stays readable over any part
of the scene.

Each glyph is authored here as a 16x16 character map (`#` white, `o` black,
`.` transparent) and shipped at twice that size, matching the chunky pointer
scale the reference client uses on modern displays.  The hotspot - the pixel
the click lands on - is authored per glyph at 16x16 scale and written doubled
into the manifest the client reads.

Run from godot-client/:  python tools/make_action_cursors.py [--preview out.png]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

SCALE = 2
WHITE = (255, 255, 255, 255)
BLACK = (0, 0, 0, 255)
CLEAR = (0, 0, 0, 0)

# Cursor order mirrors the legacy client's cursors.h ids so the two clients
# talk about the same thing when a mode is compared against the reference.
GLYPHS: dict[str, dict] = {}


def glyph(name: str, hotspot: tuple[int, int], art: str) -> None:
    rows = [row for row in art.splitlines() if row.strip()]
    if len(rows) != 16 or any(len(row) != 16 for row in rows):
        raise SystemExit(f"{name}: art must be 16 rows of 16 columns")
    GLYPHS[name] = {"hotspot": hotspot, "rows": rows}


# An open eye: inspect whatever is under the pointer.
glyph("eye", (7, 8), """
................
................
................
................
.....oooooo.....
...oo######oo...
..o##########o..
.o####oooo####o.
o####oooooo####o
o####oooooo####o
.o####oooo####o.
..o##########o..
...oo######oo...
.....oooooo.....
................
................
""")

# A speech bubble: this one talks back.
glyph("talk", (7, 6), """
................
..oooooooooooo..
.o############o.
o##############o
o##############o
o###oo#oo#oo###o
o###oo#oo#oo###o
o##############o
o##############o
.o############o.
..oooo###ooooo..
.....o###o......
....o##oo.......
....o#o.........
....oo..........
................
""")

# A sword raised point-first: the target can be fought.
glyph("attack", (7, 1), """
.......oo.......
......o##o......
......o##o......
.....o####o.....
.....o####o.....
.....o####o.....
.....o####o.....
.....o####o.....
.....o####o.....
..oooo####oooo..
.o############o.
..ooooo##ooooo..
......o##o......
.....o####o.....
.....o####o.....
......oooo......
""")

# A doorway standing open: this leads somewhere.
glyph("enter", (7, 8), """
..oooooooooooo..
.o############o.
.o#oooooooooo#o.
.o#o........o#o.
.o#o........o#o.
.o#o........o#o.
.o#o......ooo#o.
.o#o.....o##o#o.
.o#o.....o##o#o.
.o#o......ooo#o.
.o#o........o#o.
.o#o........o#o.
.o#o........o#o.
.o#o........o#o.
.ooo........ooo.
................
""")

# An open sack: goods on the ground, waiting to be taken.
glyph("pick", (7, 9), """
......oooo......
.....o####o.....
.....o####o.....
....oo####oo....
...o##oooo##o...
..o##########o..
.o############o.
.o############o.
o##############o
o##############o
o##############o
o##############o
.o############o.
..o##########o..
...oooooooooo...
................
""")

# A sprouting plant: this can be harvested.
glyph("harvest", (7, 10), """
................
..ooo......ooo..
.o###o....o###o.
o#####o..o#####o
o######oo######o
o######oo######o
.o#####oo#####o.
..o####oo####o..
...ooo####ooo...
......o##o......
......o##o......
......o##o......
......o##o......
....oo####oo....
...o########o...
...oooooooooo...
""")

# A figure mid-stride: the click walks there.
glyph("walk", (7, 3), """
......oooo......
.....o####o.....
.....o####o.....
......o##o......
.....o####o.....
....o######o....
...o##o##o##o...
..o##oo##oo##o..
..o#o.o##o.o#o..
..oo..o##o..oo..
.....o####o.....
....o##oo##o....
...o##o..o##o...
..o##o....o##o..
..o#o......o#o..
..oo........oo..
""")

# The plain pointer, for the interface itself.
glyph("arrow", (2, 1), """
.oo.............
.o#o............
.o##o...........
.o###o..........
.o####o.........
.o#####o........
.o######o.......
.o#######o......
.o########o.....
.o#####ooooo....
.o##o##o........
.o#o.o##o.......
.oo..o##o.......
......o##o......
......o##o......
.......oo.......
""")

# Two arrows passing each other: an exchange between equals.
glyph("trade", (7, 7), """
................
......oo........
.....o#o........
....o##ooooooo..
...o##########o.
....o##ooooooo..
.....o#o........
......oo........
........oo......
........o#o.....
..ooooooo##o....
.o##########o...
..ooooooo##o....
........o#o.....
........oo......
................
""")

# A hand offering a small item up to something.
glyph("use_witem", (2, 2), """
.oooo...........
.o##o...........
.o##o...........
.oooo..oooo.....
......o####o....
.ooooo#####o....
o#############o.
o#############o.
.ooooo#########o
.....o#########o
.....o#########o
.....o########o.
.....o########o.
......oooooooo..
................
................
""")

# A hand pressing: this can be worked or operated.
glyph("use", (1, 7), """
................
................
................
........oooo....
.......o####o...
.oooooo#####o...
o##############o
o##############o
.oooooo########o
......o########o
......o########o
......o########o
......o#######o.
.......ooooooo..
................
................
""")

# A wand trailing sparks: a spell is waiting for a target.
glyph("wand", (3, 3), """
...o............
.o.o.o..........
..ooo...........
ooo#ooo.........
..ooo.o.........
.o.o.o##o.......
...o..o##o......
.......o##o.....
........o##o....
.........o##o...
..........o##o..
...........o##o.
............o##o
.............o#o
..............oo
................
""")

# The text caret, for writable fields.
glyph("text", (7, 8), """
................
...oooo.oooo....
...o###o###o....
...oooo#oooo....
......o#o.......
......o#o.......
......o#o.......
......o#o.......
......o#o.......
......o#o.......
......o#o.......
......o#o.......
......o#o.......
...oooo#oooo....
...o###o###o....
...oooo.oooo....
""")

# A grasping hand, reaching from above: the click moves the item under it.
# Not part of the legacy thirteen - the reference reserved its hand for bags
# on the ground, which Eloria's sack covers - but the same visual language.
glyph("grab", (7, 7), """
..oo.oo.oo.oo...
.o##o##o##o##o..
.o##o##o##o##o..
.o############o.
.o############o.
oo############o.
o#o###########o.
o##o##########o.
.o############o.
.o###########o..
..o##########o..
...o########o...
....o######o....
....oooooooo....
................
................
""")


def render(rows: list[str]) -> Image.Image:
    image = Image.new("RGBA", (16, 16), CLEAR)
    for y, row in enumerate(rows):
        for x, cell in enumerate(row):
            if cell == "#":
                image.putpixel((x, y), WHITE)
            elif cell == "o":
                image.putpixel((x, y), BLACK)
            elif cell != ".":
                raise SystemExit(f"unknown cell {cell!r} at {x},{y}")
    return image


def build(out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest = {"scale": SCALE, "cursors": []}
    for name, spec in GLYPHS.items():
        image = render(spec["rows"]).resize((16 * SCALE, 16 * SCALE), Image.Resampling.NEAREST)
        file_name = f"cursor_{name}.png"
        image.save(out_dir / file_name)
        manifest["cursors"].append({
            "name": name,
            "file": file_name,
            "hotspot": [spec["hotspot"][0] * SCALE, spec["hotspot"][1] * SCALE],
        })
    (out_dir / "cursors.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def preview(manifest: dict, out_dir: Path, path: Path, zoom: int = 6) -> None:
    """A magnified contact sheet with the hotspot marked in red."""
    cell = 16 * SCALE * zoom
    count = len(manifest["cursors"])
    sheet = Image.new("RGBA", (count * (cell + 4), cell + 4), (72, 96, 72, 255))
    for index, entry in enumerate(manifest["cursors"]):
        icon = Image.open(out_dir / entry["file"]).resize(
            (cell, cell), Image.Resampling.NEAREST)
        sheet.alpha_composite(icon, (index * (cell + 4) + 2, 2))
        hx, hy = entry["hotspot"]
        for dy in range(zoom):
            for dx in range(zoom):
                sheet.putpixel(
                    (index * (cell + 4) + 2 + hx * zoom + dx, 2 + hy * zoom + dy),
                    (255, 64, 64, 160))
    sheet.save(path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path,
                        default=Path(__file__).resolve().parents[1] / "assets" / "ui" / "cursors")
    parser.add_argument("--preview", type=Path, default=None)
    args = parser.parse_args()
    manifest = build(args.out)
    if args.preview is not None:
        preview(manifest, args.out, args.preview)
    print(f"wrote {len(manifest['cursors'])} cursors to {args.out}")


if __name__ == "__main__":
    main()
