#include "actor_glb_runtime.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <map>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
#include "actors.h"
#include "cal_types.h"
#include "errors.h"
#include "gl_init.h"
#include "init.h"
namespace {
using json=nlohmann::json;
struct M{float v[16];}; struct V{float p[3],n[3],uv[2],w[4];uint16_t j[4];};
struct T{int node;std::vector<float>t,q;};struct C{float duration=0;bool loop=false;std::vector<T>tracks;};
struct Model{bool tried=false,ok=false;json j;std::vector<unsigned char>b;std::vector<V>v;std::vector<uint32_t>i;std::vector<int>parent,joints;std::vector<float>translation;std::vector<M>inverse;std::map<std::string,C>clips;};Model model[2];
uint32_t u32(const unsigned char*p){return p[0]|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
M ident(){M x={};x.v[0]=x.v[5]=x.v[10]=x.v[15]=1;return x;}M mul(const M&a,const M&b){M r={};for(int c=0;c<4;c++)for(int y=0;y<4;y++)for(int k=0;k<4;k++)r.v[c*4+y]+=a.v[k*4+y]*b.v[c*4+k];return r;}
M local(const float*t,const float*q){float x=q[0],y=q[1],z=q[2],w=q[3];M m=ident();m.v[0]=1-2*y*y-2*z*z;m.v[1]=2*x*y+2*w*z;m.v[2]=2*x*z-2*w*y;m.v[4]=2*x*y-2*w*z;m.v[5]=1-2*x*x-2*z*z;m.v[6]=2*y*z+2*w*x;m.v[8]=2*x*z+2*w*y;m.v[9]=2*y*z-2*w*x;m.v[10]=1-2*x*x-2*y*y;m.v[12]=t[0];m.v[13]=t[1];m.v[14]=t[2];return m;}
bool acc(Model&m,size_t ai,const unsigned char*&p,size_t&n,size_t&s,int&ct,std::string&type){if(ai>=m.j["accessors"].size())return false;const auto&a=m.j["accessors"][ai];size_t vi=a.value("bufferView",size_t(-1));if(vi>=m.j["bufferViews"].size())return false;const auto&v=m.j["bufferViews"][vi];ct=a["componentType"];type=a["type"];n=a["count"];size_t width=ct==5123?2:4,comps=type=="SCALAR"?1:type=="VEC2"?2:type=="VEC3"?3:type=="VEC4"?4:type=="MAT4"?16:0;s=v.value("byteStride",width*comps);size_t o=v.value("byteOffset",0u)+a.value("byteOffset",0u);if(!comps||o>m.b.size()||n>(m.b.size()-o)/s)return false;p=m.b.data()+o;return true;}
bool floats(Model&m,size_t ai,size_t width,std::vector<float>&out){const unsigned char*p;size_t n,s;int ct;std::string type;if(!acc(m,ai,p,n,s,ct,type)||ct!=5126)return false;size_t got=type=="SCALAR"?1:type=="VEC2"?2:type=="VEC3"?3:type=="VEC4"?4:type=="MAT4"?16:0;if(got!=width)return false;out.resize(n*width);for(size_t x=0;x<n;x++)memcpy(&out[x*width],p+x*s,width*4);return true;}
bool load(Model&m,const char*sex){m.tried=true;std::string path=std::string(datadir)+"/actors/playable/luminous_"+sex+"_quaternius_v2.glb";std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f){LOG_ERROR("Luminous GLB runtime: missing %s",path.c_str());return false;}size_t z=size_t(f.tellg());std::vector<unsigned char>all(z);f.seekg(0);if(z<20||!f.read((char*)all.data(),z)||memcmp(all.data(),"glTF",4)||u32(all.data()+4)!=2)return false;for(size_t o=12;o+8<=z;){size_t n=u32(all.data()+o);uint32_t k=u32(all.data()+o+4);o+=8;if(n>z-o)return false;if(k==0x4e4f534a)m.j=json::parse(all.begin()+o,all.begin()+o+n);else if(k==0x004e4942)m.b.assign(all.begin()+o,all.begin()+o+n);o+=n;}if(m.j.value("asset",json::object()).value("version","")!="2.0"||m.j["meshes"].empty()||m.j["skins"].empty())return false;const auto&p=m.j["meshes"][0]["primitives"][0];std::vector<float>pos,norm,uv,w;if(!floats(m,p["attributes"]["POSITION"],3,pos)||!floats(m,p["attributes"]["NORMAL"],3,norm)||!floats(m,p["attributes"]["TEXCOORD_0"],2,uv)||!floats(m,p["attributes"]["WEIGHTS_0"],4,w))return false;const unsigned char*raw;size_t n,s;int ct;std::string type;if(!acc(m,p["attributes"]["JOINTS_0"],raw,n,s,ct,type)||ct!=5123||type!="VEC4"||n!=pos.size()/3)return false;m.v.resize(n);for(size_t x=0;x<n;x++){memcpy(m.v[x].p,&pos[x*3],12);memcpy(m.v[x].n,&norm[x*3],12);memcpy(m.v[x].uv,&uv[x*2],8);memcpy(m.v[x].w,&w[x*4],16);memcpy(m.v[x].j,raw+x*s,8);}if(!acc(m,p["indices"],raw,n,s,ct,type)||type!="SCALAR"||(ct!=5123&&ct!=5125))return false;m.i.resize(n);for(size_t x=0;x<n;x++){if(ct==5123){uint16_t q;memcpy(&q,raw+x*s,2);m.i[x]=q;}else memcpy(&m.i[x],raw+x*s,4);if(m.i[x]>=m.v.size())return false;}
 const auto&skin=m.j["skins"][0];for(const auto&q:skin["joints"])m.joints.push_back(q);std::vector<float>iv;if(!floats(m,skin["inverseBindMatrices"],16,iv)||iv.size()!=m.joints.size()*16)return false;m.inverse.resize(m.joints.size());for(size_t x=0;x<m.inverse.size();x++)memcpy(m.inverse[x].v,&iv[x*16],64);m.parent.assign(m.j["nodes"].size(),-1);m.translation.assign(m.j["nodes"].size()*3,0);for(size_t x=0;x<m.j["nodes"].size();x++){const auto&node=m.j["nodes"][x];if(node.contains("translation"))for(int k=0;k<3;k++)m.translation[x*3+k]=node["translation"][k];for(const auto&q:node.value("children",json::array()))m.parent[size_t(q)]=int(x);}
 for(const auto&a:m.j.value("animations",json::array())){C c;c.loop=a.value("extras",json::object()).value("loop",false);for(const auto&ch:a["channels"]){if(ch["target"].value("path","")!="rotation")continue;const auto&samp=a["samplers"][size_t(ch["sampler"])];T t;t.node=ch["target"]["node"];if(!floats(m,samp["input"],1,t.t)||!floats(m,samp["output"],4,t.q))return false;if(!t.t.empty())c.duration=std::max(c.duration,t.t.back());c.tracks.push_back(std::move(t));}m.clips[a.value("name","")]=std::move(c);}m.ok=!m.v.empty()&&m.clips.size()>=15;LOG_INFO("Luminous GLB runtime: %s has %u vertices and %u mapped clips",path.c_str(),(unsigned)m.v.size(),(unsigned)m.clips.size());return m.ok;}
const char*clip(const actor*a){const actor_types&d=actors_defs[a->actor_type];int index=a->cur_anim.anim_index;struct X{int f;const char*n;};static const X map[]={{0,"walk"},{1,"run"},{2,"die"},{3,"die"},{4,"pain"},{5,"pain"},{6,"pick"},{7,"drop"},{8,"idle"},{9,"idle2"},{10,"sit"},{11,"harvest"},{12,"cast"},{13,"attack"},{14,"sit_down"},{15,"stand_up"},{16,"combat_idle"},{17,"idle"},{18,"combat_idle"},{39,"combat_idle"},{40,"idle"},{41,"combat_idle"},{64,"combat_idle"},{65,"idle"},{66,"combat_idle"}};for(const X&x:map)if(d.cal_frames[x.f].anim_index==index)return x.n;for(int f=19;f<=61;f++)if(d.cal_frames[f].anim_index==index)return "attack";return a->fighting?"combat_idle":"idle";}
void skin(Model&m,const C&c,float time,std::vector<M>&mat){size_t count=m.j["nodes"].size();std::vector<float>q(count*4,0);for(size_t x=0;x<count;x++)q[x*4+3]=1;float now=c.loop&&c.duration>0?fmodf(std::max(0.f,time),c.duration):std::min(std::max(0.f,time),c.duration);for(const T&t:c.tracks){if(t.t.empty()||t.node<0||size_t(t.node)>=count)continue;size_t b=std::upper_bound(t.t.begin(),t.t.end(),now)-t.t.begin(),a=b?b-1:0;if(b>=t.t.size())b=t.t.size()-1;float f=a==b?0:(now-t.t[a])/(t.t[b]-t.t[a]),*dst=&q[t.node*4];const float*qa=&t.q[a*4],*qb=&t.q[b*4];float sign=(qa[0]*qb[0]+qa[1]*qb[1]+qa[2]*qb[2]+qa[3]*qb[3])<0?-1.f:1.f,n=0;for(int k=0;k<4;k++){dst[k]=qa[k]+f*(sign*qb[k]-qa[k]);n+=dst[k]*dst[k];}n=sqrtf(n);if(n>1e-8f)for(int k=0;k<4;k++)dst[k]/=n;}std::vector<M>g(count);for(size_t x=0;x<count;x++){M l=local(&m.translation[x*3],&q[x*4]);g[x]=m.parent[x]<0?l:mul(g[m.parent[x]],l);}mat.resize(m.joints.size());for(size_t x=0;x<mat.size();x++)mat[x]=mul(g[m.joints[x]],m.inverse[x]);}
}
extern "C" int actor_glb_is_luminous(const void*p){const actor*a=(const actor*)p;return a&&a->is_enhanced_model&&(a->actor_type==0||a->actor_type==1);}
extern "C" int actor_glb_draw(void*p,unsigned int,unsigned int){actor*a=(actor*)p;if(!actor_glb_is_luminous(a))return 0;Model&m=model[a->actor_type];if(!m.tried)try{load(m,a->actor_type?"male":"female");}catch(const std::exception&e){LOG_ERROR("Luminous GLB runtime rejected actor: %s",e.what());}if(!m.ok)return 0;auto c=m.clips.find(clip(a));if(c==m.clips.end())c=m.clips.find("idle");if(c==m.clips.end())return 0;std::vector<M>mat;skin(m,c->second,a->anim_time,mat);std::vector<V>out=m.v;for(size_t x=0;x<out.size();x++){float p3[3]={},n3[3]={};for(int s=0;s<4;s++){unsigned j=out[x].j[s];float w=out[x].w[s];if(j>=mat.size()||w<=0)continue;const M&t=mat[j];for(int k=0;k<3;k++){p3[k]+=w*(t.v[12+k]+t.v[k]*m.v[x].p[0]+t.v[4+k]*m.v[x].p[1]+t.v[8+k]*m.v[x].p[2]);n3[k]+=w*(t.v[k]*m.v[x].n[0]+t.v[4+k]*m.v[x].n[1]+t.v[8+k]*m.v[x].n[2]);}}memcpy(out[x].p,p3,12);float n=sqrtf(n3[0]*n3[0]+n3[1]*n3[1]+n3[2]*n3[2]);if(n>1e-8f)for(int k=0;k<3;k++)out[x].n[k]=n3[k]/n;}glEnableClientState(GL_VERTEX_ARRAY);glEnableClientState(GL_NORMAL_ARRAY);glEnableClientState(GL_TEXTURE_COORD_ARRAY);glVertexPointer(3,GL_FLOAT,sizeof(V),out.data()->p);glNormalPointer(GL_FLOAT,sizeof(V),out.data()->n);glTexCoordPointer(2,GL_FLOAT,sizeof(V),out.data()->uv);glDrawElements(GL_TRIANGLES,(GLsizei)m.i.size(),GL_UNSIGNED_INT,m.i.data());return 1;}
extern "C" void actor_glb_runtime_destroy(){model[0]=Model();model[1]=Model();}
