#include "actor_glb_runtime.h"
#include <algorithm>
#include <cmath>
#include <cctype>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <functional>
#include <map>
#include <stdexcept>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
#include "actors_list.h"
#include "cal_types.h"
#include "errors.h"
#include "gl_init.h"
#include "init.h"
#include "textures.h"
namespace {
using json=nlohmann::json;
struct M{float v[16];};struct V{float p[3],n[3],uv[2],w[4];uint16_t j[4];};
struct Pose{float t[3],r[4],s[3];};struct Part{std::vector<V>v;std::vector<uint32_t>i;int tex=-1;float color[4]={1,1,1,1};bool blend=false;};
struct Track{int node,path;bool step;std::vector<float>time,value;float source_rest[4];};struct Clip{float duration=0;bool loop=false;std::vector<Track>tracks;};
struct Doc{json j;std::vector<unsigned char>b;};struct A{const unsigned char*p;size_t n,stride,width;int ct;};
struct Model{bool tried=false,ok=false;std::vector<Part>parts;std::vector<int>parent,joints;std::vector<Pose>rest;std::vector<M>inverse;std::map<std::string,Clip>clips;};Model models[2];
uint32_t u32(const unsigned char*p){return p[0]|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
std::vector<unsigned char>file(const std::string&p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("cannot open "+p);size_t z=size_t(f.tellg());std::vector<unsigned char>d(z);f.seekg(0);if(!z||!f.read((char*)d.data(),z))throw std::runtime_error("cannot read "+p);return d;}
Doc document(const std::string&p){Doc d;auto raw=file(p);std::string dir=p.substr(0,p.find_last_of("/\\")+1);if(raw.size()>=12&&!memcmp(raw.data(),"glTF",4)){if(u32(raw.data()+4)!=2||u32(raw.data()+8)!=raw.size())throw std::runtime_error("invalid GLB");for(size_t o=12;o+8<=raw.size();){size_t n=u32(raw.data()+o);uint32_t k=u32(raw.data()+o+4);o+=8;if(n>raw.size()-o)throw std::runtime_error("truncated GLB");if(k==0x4e4f534a)d.j=json::parse(raw.begin()+o,raw.begin()+o+n);else if(k==0x004e4942)d.b.assign(raw.begin()+o,raw.begin()+o+n);o+=n;}}else{d.j=json::parse(raw.begin(),raw.end());std::string uri=d.j["buffers"][0]["uri"];if(uri.find("..")!=std::string::npos||uri.find(':')!=std::string::npos)throw std::runtime_error("unsafe buffer URI");d.b=file(dir+uri);}if(d.j.value("asset",json::object()).value("version","")!="2.0"||d.j["buffers"][0]["byteLength"].get<size_t>()>d.b.size())throw std::runtime_error("invalid glTF buffer");return d;}
A acc(const Doc&d,size_t x){const auto&a=d.j["accessors"].at(x);const auto&v=d.j["bufferViews"].at(size_t(a["bufferView"]));A r={};r.n=a["count"];r.ct=a["componentType"];std::string t=a["type"];r.width=t=="SCALAR"?1:t=="VEC2"?2:t=="VEC3"?3:t=="VEC4"?4:t=="MAT4"?16:0;size_t z=r.ct==5121?1:r.ct==5123?2:4;r.stride=v.value("byteStride",z*r.width);size_t o=v.value("byteOffset",0u)+a.value("byteOffset",0u);if(!r.width||o>d.b.size()||r.n>(d.b.size()-o)/r.stride)throw std::runtime_error("accessor outside buffer");r.p=d.b.data()+o;return r;}
std::vector<float>floats(const Doc&d,size_t x,size_t w){A a=acc(d,x);if(a.ct!=5126||a.width!=w)throw std::runtime_error("expected float accessor");std::vector<float>r(a.n*w);for(size_t i=0;i<a.n;i++)memcpy(&r[i*w],a.p+i*a.stride,w*4);return r;}
M ident(){M r={};r.v[0]=r.v[5]=r.v[10]=r.v[15]=1;return r;}M mul(const M&a,const M&b){M r={};for(int c=0;c<4;c++)for(int y=0;y<4;y++)for(int k=0;k<4;k++)r.v[c*4+y]+=a.v[k*4+y]*b.v[c*4+k];return r;}
Pose pose(const json&n){Pose p={{0,0,0},{0,0,0,1},{1,1,1}};if(n.contains("translation"))for(int i=0;i<3;i++)p.t[i]=n["translation"][i];if(n.contains("rotation"))for(int i=0;i<4;i++)p.r[i]=n["rotation"][i];if(n.contains("scale"))for(int i=0;i<3;i++)p.s[i]=n["scale"][i];return p;}
M local(const Pose&p){float x=p.r[0],y=p.r[1],z=p.r[2],w=p.r[3];M m=ident();m.v[0]=(1-2*y*y-2*z*z)*p.s[0];m.v[1]=(2*x*y+2*w*z)*p.s[0];m.v[2]=(2*x*z-2*w*y)*p.s[0];m.v[4]=(2*x*y-2*w*z)*p.s[1];m.v[5]=(1-2*x*x-2*z*z)*p.s[1];m.v[6]=(2*y*z+2*w*x)*p.s[1];m.v[8]=(2*x*z+2*w*y)*p.s[2];m.v[9]=(2*y*z-2*w*x)*p.s[2];m.v[10]=(1-2*x*x-2*y*y)*p.s[2];m.v[12]=p.t[0];m.v[13]=p.t[1];m.v[14]=p.t[2];return m;}
void qmul(const float*a,const float*b,float*r){r[0]=a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1];r[1]=a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0];r[2]=a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3];r[3]=a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2];}
void material(const Doc&d,const std::string&dir,size_t mi,Part&p){if(mi>=d.j.value("materials",json::array()).size())return;const auto&m=d.j["materials"][mi];auto mr=m.value("pbrMetallicRoughness",json::object());auto c=mr.value("baseColorFactor",json::array({1,1,1,1}));if(c.size()==4)for(int k=0;k<4;k++)p.color[k]=c[k];p.blend=m.value("alphaMode","OPAQUE")=="BLEND";if(!mr.contains("baseColorTexture"))return;size_t ti=mr["baseColorTexture"]["index"],ii=d.j["textures"].at(ti)["source"];std::string uri=d.j["images"].at(ii)["uri"];if(uri.find("..")!=std::string::npos||uri.find(':')!=std::string::npos)throw std::runtime_error("unsafe image URI");p.tex=load_texture_cached((dir+uri).c_str(),tt_mesh);}
void primitive(const Doc&d,const json&s,const std::string&dir,Part&p){const auto&a=s["attributes"];auto pos=floats(d,a["POSITION"],3),nor=floats(d,a["NORMAL"],3),uv=floats(d,a["TEXCOORD_0"],2),wei=floats(d,a["WEIGHTS_0"],4);A joi=acc(d,a["JOINTS_0"]);size_t n=pos.size()/3;if(nor.size()/3!=n||uv.size()/2!=n||wei.size()/4!=n||joi.n!=n||joi.width!=4||(joi.ct!=5121&&joi.ct!=5123))throw std::runtime_error("invalid vertex attributes");p.v.resize(n);for(size_t x=0;x<n;x++){memcpy(p.v[x].p,&pos[x*3],12);memcpy(p.v[x].n,&nor[x*3],12);memcpy(p.v[x].uv,&uv[x*2],8);memcpy(p.v[x].w,&wei[x*4],16);for(int k=0;k<4;k++)p.v[x].j[k]=joi.ct==5121?joi.p[x*joi.stride+k]:reinterpret_cast<const uint16_t*>(joi.p+x*joi.stride)[k];}A ind=acc(d,s["indices"]);if(ind.width!=1||(ind.ct!=5123&&ind.ct!=5125))throw std::runtime_error("invalid indices");p.i.resize(ind.n);for(size_t x=0;x<ind.n;x++)p.i[x]=ind.ct==5123?*reinterpret_cast<const uint16_t*>(ind.p+x*ind.stride):*reinterpret_cast<const uint32_t*>(ind.p+x*ind.stride);if(s.contains("material"))material(d,dir,s["material"],p);}
void animations(Model&m,const std::string&path,const std::map<std::string,int>&names){Doc d=document(path);std::vector<Pose>rest;std::vector<int>target(d.j["nodes"].size(),-1);for(size_t x=0;x<target.size();x++){rest.push_back(pose(d.j["nodes"][x]));std::string n=d.j["nodes"][x].value("name","");std::transform(n.begin(),n.end(),n.begin(),[](unsigned char c){return std::tolower(c);});auto f=names.find(n);if(f!=names.end())target[x]=f->second;}for(const auto&source:d.j.value("animations",json::array())){Clip c;std::string name=source.value("name","");c.loop=name=="Idle_A"||name=="Idle_Subtle"||name=="Walk"||name=="Jog"||name=="Fighting_Idle"||name=="Sitting_Idle";for(const auto&channel:source["channels"]){size_t sn=channel["target"]["node"];if(sn>=target.size()||target[sn]<0)continue;std::string path=channel["target"].value("path","");if(path!="rotation"&&path!="translation")continue;const auto&sampler=source["samplers"][size_t(channel["sampler"])];Track t;t.node=target[sn];t.path=path=="rotation"?1:0;t.step=sampler.value("interpolation","LINEAR")=="STEP";t.time=floats(d,sampler["input"],1);t.value=floats(d,sampler["output"],t.path?4:3);memcpy(t.source_rest,t.path?rest[sn].r:rest[sn].t,(t.path?4:3)*4);if(!t.time.empty())c.duration=std::max(c.duration,t.time.back());c.tracks.push_back(std::move(t));}if(!name.empty())m.clips[name]=std::move(c);}}
bool load(Model&m,const char*sex){m.tried=true;std::string dir=std::string(datadir)+"/actors/playable/native/",name=std::string("Superhero_")+(strcmp(sex,"female")?"Male":"Female")+"_FullBody.gltf";Doc d=document(dir+name);const auto&nodes=d.j["nodes"];m.parent.assign(nodes.size(),-1);std::map<std::string,int>names;for(size_t x=0;x<nodes.size();x++){m.rest.push_back(pose(nodes[x]));std::string n=nodes[x].value("name","");std::transform(n.begin(),n.end(),n.begin(),[](unsigned char c){return std::tolower(c);});if(!n.empty())names[n]=x;for(const auto&c:nodes[x].value("children",json::array()))m.parent[size_t(c)]=x;}const auto&skin=d.j["skins"][0];for(const auto&j:skin["joints"])m.joints.push_back(j);auto inv=floats(d,skin["inverseBindMatrices"],16);if(inv.size()!=m.joints.size()*16)throw std::runtime_error("invalid inverse binds");m.inverse.resize(m.joints.size());for(size_t x=0;x<m.inverse.size();x++)memcpy(m.inverse[x].v,&inv[x*16],64);for(const auto&node:nodes)if(node.contains("mesh"))for(const auto&p:d.j["meshes"][size_t(node["mesh"])]["primitives"]){m.parts.emplace_back();primitive(d,p,dir,m.parts.back());}animations(m,dir+"Universal_Animation_Library.glb",names);m.ok=m.parts.size()>=3&&m.joints.size()==65&&m.clips.size()>=120;LOG_INFO("Native luminous glTF: %s, %u primitives, %u joints, %u clips",name.c_str(),(unsigned)m.parts.size(),(unsigned)m.joints.size(),(unsigned)m.clips.size());return m.ok;}
const char*clip(const actor*a){const actor_types&d=actors_defs[a->actor_type];int i=a->cur_anim.anim_index;struct X{int f;const char*n;};static const X map[]={{0,"Walk"},{1,"Jog"},{2,"Death_A"},{3,"Death_A"},{4,"Hit_Chest"},{5,"Hit_Chest"},{6,"PickUp_Table"},{7,"Throw_Object"},{8,"Idle_A"},{9,"Idle_Subtle"},{10,"Sitting_Idle"},{11,"Farm_Harvest"},{12,"Spell_Simple_Shoot"},{13,"Sword_Attack"},{14,"Sitting_Enter"},{15,"Sitting_Exit"},{16,"Fighting_Idle"},{17,"Idle_A"},{18,"Fighting_Idle"},{39,"Fighting_Idle"},{40,"Idle_A"},{41,"Fighting_Idle"},{64,"Fighting_Idle"},{65,"Idle_A"},{66,"Fighting_Idle"}};for(const X&x:map)if(d.cal_frames[x.f].anim_index==i)return x.n;for(int f=19;f<=61;f++)if(d.cal_frames[f].anim_index==i)return "Sword_Attack";return a->fighting?"Fighting_Idle":"Idle_A";}
void sample(const Track&t,float now,float*out){size_t w=t.path?4:3,b=std::upper_bound(t.time.begin(),t.time.end(),now)-t.time.begin(),a=b?b-1:0;if(b>=t.time.size())b=t.time.size()-1;float f=t.step||a==b?0:(now-t.time[a])/(t.time[b]-t.time[a]),sign=1;if(w==4){const float*x=&t.value[a*w],*y=&t.value[b*w];if(x[0]*y[0]+x[1]*y[1]+x[2]*y[2]+x[3]*y[3]<0)sign=-1;}float n=0;for(size_t k=0;k<w;k++){out[k]=t.value[a*w+k]+f*(sign*t.value[b*w+k]-t.value[a*w+k]);n+=out[k]*out[k];}if(w==4&&n>1e-12){n=sqrtf(n);for(int k=0;k<4;k++)out[k]/=n;}}
void matrices(const Model&m,const Clip&c,float time,std::vector<M>&out){std::vector<Pose>p=m.rest;float now=c.loop&&c.duration>0?fmodf(std::max(0.f,time),c.duration):std::min(std::max(0.f,time),c.duration);for(const Track&t:c.tracks){float v[4]={0,0,0,1};sample(t,now,v);if(!t.path)for(int k=0;k<3;k++)p[t.node].t[k]=m.rest[t.node].t[k]+v[k]-t.source_rest[k];else{float inv[4]={-t.source_rest[0],-t.source_rest[1],-t.source_rest[2],t.source_rest[3]},delta[4],target[4];qmul(v,inv,delta);qmul(delta,m.rest[t.node].r,target);memcpy(p[t.node].r,target,16);}}std::vector<M>g(p.size());std::vector<char>done(p.size());std::function<const M&(size_t)>resolve=[&](size_t x)->const M&{if(!done[x]){M l=local(p[x]);g[x]=m.parent[x]<0?l:mul(resolve(m.parent[x]),l);done[x]=1;}return g[x];};out.resize(m.joints.size());for(size_t x=0;x<out.size();x++)out[x]=mul(resolve(m.joints[x]),m.inverse[x]);}
void draw(const Part&p,const std::vector<M>&mat){std::vector<V>v=p.v;for(size_t x=0;x<v.size();x++){float q[3]={},n[3]={};for(int s=0;s<4;s++){unsigned j=p.v[x].j[s];float w=p.v[x].w[s];if(j>=mat.size()||w<=0)continue;const M&t=mat[j];for(int k=0;k<3;k++){q[k]+=w*(t.v[12+k]+t.v[k]*p.v[x].p[0]+t.v[4+k]*p.v[x].p[1]+t.v[8+k]*p.v[x].p[2]);n[k]+=w*(t.v[k]*p.v[x].n[0]+t.v[4+k]*p.v[x].n[1]+t.v[8+k]*p.v[x].n[2]);}}memcpy(v[x].p,q,12);float z=sqrtf(n[0]*n[0]+n[1]*n[1]+n[2]*n[2]);if(z>1e-8)for(int k=0;k<3;k++)v[x].n[k]=n[k]/z;}if(p.tex>=0)bind_texture(p.tex);glColor4fv(p.color);if(p.blend){glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);}glEnableClientState(GL_VERTEX_ARRAY);glEnableClientState(GL_NORMAL_ARRAY);glEnableClientState(GL_TEXTURE_COORD_ARRAY);glVertexPointer(3,GL_FLOAT,sizeof(V),v.data()->p);glNormalPointer(GL_FLOAT,sizeof(V),v.data()->n);glTexCoordPointer(2,GL_FLOAT,sizeof(V),v.data()->uv);glDrawElements(GL_TRIANGLES,(GLsizei)p.i.size(),GL_UNSIGNED_INT,p.i.data());if(p.blend)glDisable(GL_BLEND);glColor4f(1,1,1,1);}
}
extern "C" int actor_glb_is_luminous(const void*p){const actor*a=(const actor*)p;return a&&a->is_enhanced_model&&(a->actor_type==0||a->actor_type==1);}
extern "C" int actor_glb_draw(void*p,unsigned int,unsigned int){actor*a=(actor*)p;if(!actor_glb_is_luminous(a))return 0;Model&m=models[a->actor_type];if(!m.tried)try{load(m,a->actor_type?"male":"female");}catch(const std::exception&e){LOG_ERROR("Native luminous glTF rejected: %s",e.what());}if(!m.ok)return 0;auto c=m.clips.find(clip(a));if(c==m.clips.end())c=m.clips.find("Idle_A");if(c==m.clips.end())return 0;std::vector<M>mat;matrices(m,c->second,a->anim_time,mat);glPushMatrix();glRotatef(90,1,0,0);for(const Part&part:m.parts)draw(part,mat);glPopMatrix();return 1;}
extern "C" void actor_glb_runtime_destroy(){models[0]=Model();models[1]=Model();}
