#include "world_glb_renderer.h"
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
#include "errors.h"
#include "bbox_tree.h"
#include "draw_scene.h"
#include "gl_init.h"
#include "textures.h"
#include "main.h"
namespace {
using json=nlohmann::json;
struct V{float p[3],n[3],uv[2],color[4];};struct P{std::vector<V>v;std::vector<uint32_t>i;GLuint vb=0,ib=0;Uint32 tex=0;float color[4]={1,1,1,1},cutoff=.5f,min[3],max[3],scroll[2]={0,0},pulse=0;unsigned effect=0;bool textured=false,blend=false,mask=false,two=false,additive=false;};struct I{size_t p;float m[16];AABBOX bbox;};
std::vector<P> ps;std::vector<std::vector<size_t>> meshes;std::vector<I> is;std::vector<unsigned char> bin;json j;std::string folder;float convert_m[16];
uint32_t u32(const unsigned char*p){return p[0]|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}void ident(float*m){memset(m,0,64);m[0]=m[5]=m[10]=m[15]=1;}
void mul(const float*a,const float*b,float*o){float r[16];for(int c=0;c<4;c++)for(int y=0;y<4;y++){r[c*4+y]=0;for(int k=0;k<4;k++)r[c*4+y]+=a[k*4+y]*b[c*4+k];}memcpy(o,r,64);}
bool read_glb(const char*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)return false;size_t n=size_t(f.tellg());std::vector<unsigned char>b(n);f.seekg(0);if(n&&!f.read((char*)b.data(),n))return false;if(n<20||u32(b.data())!=0x46546c67)return false;for(size_t o=12;o+8<=n;){uint32_t z=u32(b.data()+o),t=u32(b.data()+o+4);o+=8;if(z>n-o)return false;if(t==0x4e4f534a)j=json::parse(b.begin()+o,b.begin()+o+z);else if(t==0x004e4942)bin.assign(b.begin()+o,b.begin()+o+z);o+=z;}return j.is_object();}
size_t comps(const std::string&t){return t=="SCALAR"?1:t=="VEC2"?2:t=="VEC3"?3:t=="VEC4"?4:0;}size_t bytes(int t){return t==5121?1:t==5123?2:t==5125||t==5126?4:0;}
bool acc(size_t a,const unsigned char*&p,size_t&count,size_t&stride,size_t&c,int&type){if(a>=j["accessors"].size())return false;json x=j["accessors"][a];if(!x.contains("bufferView")||x.contains("sparse"))return false;size_t vi=x["bufferView"];if(vi>=j["bufferViews"].size())return false;json v=j["bufferViews"][vi];type=x["componentType"];c=comps(x["type"]);size_t w=bytes(type);count=x["count"];stride=v.value("byteStride",w*c);size_t off=v.value("byteOffset",0u)+x.value("byteOffset",0u);if(!w||!c||!count||stride<w*c||off>bin.size()||count>(bin.size()-off)/stride)return false;p=bin.data()+off;return true;}
bool floats(size_t a,size_t want,std::vector<float>&out){const unsigned char*p;size_t n,s,c;int t;if(!acc(a,p,n,s,c,t)||c!=want||t!=5126)return false;out.resize(n*c);for(size_t x=0;x<n;x++)memcpy(&out[x*c],p+x*s,c*4);return true;}
bool inds(size_t a,std::vector<uint32_t>&out){const unsigned char*p;size_t n,s,c;int t;if(!acc(a,p,n,s,c,t)||c!=1||(t!=5121&&t!=5123&&t!=5125))return false;out.resize(n);for(size_t x=0;x<n;x++){if(t==5121)out[x]=p[x*s];else if(t==5123){uint16_t q;memcpy(&q,p+x*s,2);out[x]=q;}else memcpy(&out[x],p+x*s,4);}return true;}
void node_m(const json&n,float*m){ident(m);if(n.contains("matrix")){for(int x=0;x<16;x++)m[x]=n["matrix"][x];return;}float t[16],r[16],s[16];ident(t);ident(r);ident(s);if(n.contains("translation"))for(int x=0;x<3;x++)t[12+x]=n["translation"][x];if(n.contains("scale"))for(int x=0;x<3;x++)s[x*5]=n["scale"][x];if(n.contains("rotation")){float x=n["rotation"][0],y=n["rotation"][1],z=n["rotation"][2],w=n["rotation"][3];r[0]=1-2*y*y-2*z*z;r[1]=2*x*y+2*w*z;r[2]=2*x*z-2*w*y;r[4]=2*x*y-2*w*z;r[5]=1-2*x*x-2*z*z;r[6]=2*y*z+2*w*x;r[8]=2*x*z+2*w*y;r[9]=2*y*z-2*w*x;r[10]=1-2*x*x-2*y*y;}mul(t,r,m);mul(m,s,m);}
bool nonvisual(const json&n){std::string name=n.value("name","");return name=="Collision"||name=="Markers"||name.rfind("COLLISION_",0)==0||name.rfind("Spawn_",0)==0||name.rfind("Camera_",0)==0||name.rfind("POI_",0)==0;}
void visit(size_t ni,const float*parent,int depth){if(depth>128||ni>=j["nodes"].size()||nonvisual(j["nodes"][ni]))return;float local[16],world[16],final[16];node_m(j["nodes"][ni],local);mul(parent,local,world);if(j["nodes"][ni].contains("mesh")){size_t mi=j["nodes"][ni]["mesh"];if(mi<meshes.size()){mul(convert_m,world,final);for(size_t p:meshes[mi]){I x;x.p=p;memcpy(x.m,final,64);for(int a=0;a<3;a++){x.bbox.bbmin[a]=1e30f;x.bbox.bbmax[a]=-1e30f;}for(int c=0;c<8;c++){float q[3]={c&1?ps[p].max[0]:ps[p].min[0],c&2?ps[p].max[1]:ps[p].min[1],c&4?ps[p].max[2]:ps[p].min[2]};for(int a=0;a<3;a++){float v=final[12+a]+final[a]*q[0]+final[4+a]*q[1]+final[8+a]*q[2];x.bbox.bbmin[a]=std::min(x.bbox.bbmin[a],v);x.bbox.bbmax[a]=std::max(x.bbox.bbmax[a],v);}}is.push_back(x);}}}for(const auto&c:j["nodes"][ni].value("children",json::array()))visit(c.get<size_t>(),world,depth+1);}
}
static int world_glb_load_impl(const char*path,float units,const float origin[3]){world_glb_destroy();if(!read_glb(path))return 0;folder=path;size_t slash=folder.find_last_of("/\\");folder=slash==std::string::npos?".":folder.substr(0,slash);meshes.resize(j["meshes"].size());
 for(size_t mi=0;mi<meshes.size();mi++)for(const auto&x:j["meshes"][mi]["primitives"]){if(x.value("mode",4)!=4||!x["attributes"].contains("POSITION"))continue;std::vector<float>pos,norm,uv,colors;if(!floats(x["attributes"]["POSITION"],3,pos))return 0;floats(x["attributes"].value("NORMAL",size_t(-1)),3,norm);floats(x["attributes"].value("TEXCOORD_0",size_t(-1)),2,uv);size_t cc=0;if(x["attributes"].contains("COLOR_0")){if(floats(x["attributes"]["COLOR_0"],4,colors))cc=4;else if(floats(x["attributes"]["COLOR_0"],3,colors))cc=3;}P p;for(int a=0;a<3;a++){p.min[a]=1e30f;p.max[a]=-1e30f;}p.v.resize(pos.size()/3);for(size_t n=0;n<p.v.size();n++){memcpy(p.v[n].p,&pos[n*3],12);for(int a=0;a<3;a++){p.min[a]=std::min(p.min[a],p.v[n].p[a]);p.max[a]=std::max(p.max[a],p.v[n].p[a]);}p.v[n].n[0]=norm.empty()?0:norm[n*3];p.v[n].n[1]=norm.empty()?0:norm[n*3+1];p.v[n].n[2]=norm.empty()?0:norm[n*3+2];p.v[n].uv[0]=uv.empty()?0:uv[n*2];p.v[n].uv[1]=uv.empty()?0:uv[n*2+1];for(int a=0;a<4;a++)p.v[n].color[a]=(cc&&a<int(cc))?colors[n*cc+a]:1;}if(x.contains("indices")){if(!inds(x["indices"],p.i))return 0;}else{p.i.resize(p.v.size());for(size_t n=0;n<p.i.size();n++)p.i[n]=n;}if(std::any_of(p.i.begin(),p.i.end(),[&](uint32_t q){return q>=p.v.size();}))return 0;if(norm.empty()){for(size_t q=0;q+2<p.i.size();q+=3){V&a=p.v[p.i[q]],&b=p.v[p.i[q+1]],&c=p.v[p.i[q+2]];float ux=b.p[0]-a.p[0],uy=b.p[1]-a.p[1],uz=b.p[2]-a.p[2],vx=c.p[0]-a.p[0],vy=c.p[1]-a.p[1],vz=c.p[2]-a.p[2],nn[3]={uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx};for(int k=0;k<3;k++){a.n[k]+=nn[k];b.n[k]+=nn[k];c.n[k]+=nn[k];}}for(V&v:p.v){float l=std::sqrt(v.n[0]*v.n[0]+v.n[1]*v.n[1]+v.n[2]*v.n[2]);if(l>1e-8f)for(int k=0;k<3;k++)v.n[k]/=l;else v.n[1]=1;}}
  if(x.contains("material")&&size_t(x["material"])<j.value("materials",json::array()).size()){
   const auto&m=j["materials"][size_t(x["material"])];if(m.contains("alphaMode")&&!m["alphaMode"].is_string())return 0;std::string material=m.value("name","");p.effect=material=="water"?1:material=="waterfall"?2:material=="landmark-energy"?3:0;std::string alpha=m.value("alphaMode","OPAQUE");p.blend=alpha=="BLEND";p.mask=alpha=="MASK";p.cutoff=m.value("alphaCutoff",.5f);p.two=m.value("doubleSided",false);auto mr=m.value("pbrMetallicRoughness",json::object());auto f=mr.value("baseColorFactor",json::array({1,1,1,1}));if(f.size()==4)for(int k=0;k<4;k++)p.color[k]=f[k];
   if(mr.contains("baseColorTexture")){size_t ti=mr["baseColorTexture"]["index"];if(ti<j.value("textures",json::array()).size()){size_t ii=j["textures"][ti]["source"];if(ii<j.value("images",json::array()).size()&&j["images"][ii].contains("uri")){std::string uri=j["images"][ii]["uri"];if(uri.find("..")==std::string::npos&&uri.find(':')==std::string::npos){p.tex=load_texture_cached((folder+"/"+uri).c_str(),tt_mesh);p.textured=true;LOG_DEBUG("GLB material '%s' base color '%s' handle %u",material.c_str(),uri.c_str(),p.tex);}}}}
  }
  for(V&v:p.v)for(int a=0;a<4;a++)v.color[a]*=p.color[a];
  if(use_vertex_buffers){ELglGenBuffersARB(1,&p.vb);ELglBindBufferARB(GL_ARRAY_BUFFER_ARB,p.vb);ELglBufferDataARB(GL_ARRAY_BUFFER_ARB,p.v.size()*sizeof(V),p.v.data(),GL_STATIC_DRAW_ARB);ELglGenBuffersARB(1,&p.ib);ELglBindBufferARB(GL_ELEMENT_ARRAY_BUFFER_ARB,p.ib);ELglBufferDataARB(GL_ELEMENT_ARRAY_BUFFER_ARB,p.i.size()*4,p.i.data(),GL_STATIC_DRAW_ARB);}meshes[mi].push_back(ps.size());ps.push_back(p);}
 ident(convert_m);convert_m[0]=1/units;convert_m[5]=0;convert_m[6]=1/units;convert_m[9]=-1/units;convert_m[10]=0;convert_m[12]=origin[0];convert_m[13]=origin[1];convert_m[14]=origin[2];float root[16];ident(root);size_t si=j.value("scene",0u);if(si>=j.value("scenes",json::array()).size())return 0;for(const auto&n:j["scenes"][si]["nodes"])visit(n.get<size_t>(),root,0);LOG_INFO("GLB runtime: %u primitives, %u instances",(unsigned)ps.size(),(unsigned)is.size());return !is.empty();}
extern "C" int world_glb_load(const char*path,float units,const float origin[3]){try{return world_glb_load_impl(path,units,origin);}catch(const std::exception&e){LOG_ERROR("GLB runtime rejected '%s': %s",path?path:"",e.what());world_glb_destroy();return 0;}catch(...){LOG_ERROR("GLB runtime rejected '%s': unknown parser error",path?path:"");world_glb_destroy();return 0;}}
extern "C" void world_glb_set_material_effects(float wu,float wv,float fu,float fv,float pulse){for(P&p:ps){if(p.effect==1){p.scroll[0]=wu;p.scroll[1]=wv;}else if(p.effect==2){p.scroll[0]=fu;p.scroll[1]=fv;}else if(p.effect==3){p.pulse=pulse;p.additive=pulse>0;p.blend=p.blend||p.additive;}}}
extern "C" void world_glb_draw(int transparent){
 static bool first=true;GLboolean detail_enabled;ELglActiveTextureARB(detail_unit);detail_enabled=glIsEnabled(GL_TEXTURE_2D);glDisable(GL_TEXTURE_2D);ELglActiveTextureARB(base_unit);set_current_frustum(INTERSECTION_TYPE_DEFAULT);if(first){LOG_INFO("GLB runtime: beginning first draw");first=false;}
 for(const I&x:is){P&p=ps[x.p];if(p.blend!=bool(transparent)||!aabb_in_frustum(x.bbox))continue;if(p.two)glDisable(GL_CULL_FACE);else glEnable(GL_CULL_FACE);if(transparent){glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,p.additive?GL_ONE:GL_ONE_MINUS_SRC_ALPHA);}if(p.mask){glEnable(GL_ALPHA_TEST);glAlphaFunc(GL_GREATER,p.cutoff);}float pulse=p.pulse>0?.78f+.22f*std::sin(cur_time*.001f*p.pulse*6.2831853f):1.f;glColor4f(p.color[0]*pulse,p.color[1]*pulse,p.color[2]*pulse,p.color[3]);if(p.textured){glEnable(GL_TEXTURE_2D);bind_texture(p.tex);}else glDisable(GL_TEXTURE_2D);bool scroll=p.scroll[0]!=0||p.scroll[1]!=0;if(scroll){glMatrixMode(GL_TEXTURE);glPushMatrix();glTranslatef(cur_time*.001f*p.scroll[0],cur_time*.001f*p.scroll[1],0);glMatrixMode(GL_MODELVIEW);}glPushMatrix();glMultMatrixf(x.m);const char*base=p.vb?(const char*)0:(const char*)p.v.data();if(ELglBindBufferARB){ELglBindBufferARB(GL_ARRAY_BUFFER_ARB,p.vb);ELglBindBufferARB(GL_ELEMENT_ARRAY_BUFFER_ARB,p.ib);}glEnableClientState(GL_VERTEX_ARRAY);glVertexPointer(3,GL_FLOAT,sizeof(V),base+offsetof(V,p));glEnableClientState(GL_NORMAL_ARRAY);glNormalPointer(GL_FLOAT,sizeof(V),base+offsetof(V,n));glEnableClientState(GL_TEXTURE_COORD_ARRAY);glTexCoordPointer(2,GL_FLOAT,sizeof(V),base+offsetof(V,uv));if(p.pulse>0)glDisableClientState(GL_COLOR_ARRAY);else{glEnableClientState(GL_COLOR_ARRAY);glColorPointer(4,GL_FLOAT,sizeof(V),base+offsetof(V,color));}glDrawElements(GL_TRIANGLES,(GLsizei)p.i.size(),GL_UNSIGNED_INT,p.ib?(const void*)0:(const void*)p.i.data());glPopMatrix();if(scroll){glMatrixMode(GL_TEXTURE);glPopMatrix();glMatrixMode(GL_MODELVIEW);}if(p.mask)glDisable(GL_ALPHA_TEST);}
 if(transparent)glDisable(GL_BLEND);glDisableClientState(GL_COLOR_ARRAY);if(ELglBindBufferARB){ELglBindBufferARB(GL_ARRAY_BUFFER_ARB,0);ELglBindBufferARB(GL_ELEMENT_ARRAY_BUFFER_ARB,0);}glColor4f(1,1,1,1);ELglActiveTextureARB(detail_unit);if(detail_enabled)glEnable(GL_TEXTURE_2D);ELglActiveTextureARB(base_unit);
}
extern "C" void world_glb_destroy(){for(P&p:ps){if(p.vb&&ELglDeleteBuffersARB)ELglDeleteBuffersARB(1,&p.vb);if(p.ib&&ELglDeleteBuffersARB)ELglDeleteBuffersARB(1,&p.ib);}ps.clear();meshes.clear();is.clear();bin.clear();j=json();}
