"""Crownwater's secrets: what the drowned crown keeps under its islets."""
from secretrooms import Secret

REGION = "crownwater"
NAME = "Crownwater Secrets"
PALETTE = {"floor": "cobble_paving", "wall": "ashlar", "ceil": "ashlar", "rock": "cliff_rock",
           "stone": "ashlar", "timber": "timber_grey", "water": "water_lake", "crystal": "blue_crystal",
           "node": "blue_crystal", "turf": "shore_shingle"}
PROP_PALETTE = {"rock": "cliff_rock", "bark": "bark_dark", "stone": "ashlar", "timber": "timber_grey", "dark": "bark_dark"}

SECRETS = [
    Secret("crown-pearl-hollow", "The Pearl Hollow", "grotto", "tide_cave", "crownwater-pavilion-pavilion_east", (10.0, 8.0),
           resources=(("Crownwater Pearl", 4), ("Shorebank Shell", 4)),
           note="A tide cave under the east pavilion where the pearl oysters bed."),
    Secret("crown-kelp-garden", "The Kelp Garden", "garden", "drain_grate", "crownwater-pavilion-pavilion_south", (-10.0, 6.0),
           resources=(("Tidewrack Kelp", 4), ("Mirror Reed", 4), ("Deep Lake Clay", 3), ("Shorebank Shell", 3)),
           area=("harvest_speed", 2),
           note="Kelp and reed in stone beds fed by the lake, out of the wind."),
    Secret("crown-customs-cache", "The Customs Cache", "cache", "drain_grate", None, (2.5, 2.5),
           door_map="drowned_crown", door_space="customs_hall.bonded_store",
           resources=(("Crownwater Pearl", 2), ("Tidewrack Kelp", 3)),
           note="The customs officers' own cellar: a chest, a bench, and pearls not on any ledger."),
    Secret("crown-campanile-vault", "The Campanile Vault", "vault", "cracked_slab", "crownwater-campanile", (8.0, 8.0), key="Storage Token",
           texts=(("The drowned court", "The court is swept. Someone sweeps it. What is made over it counts double, the sexton says, because the court is listening."),),
           note="Under the bell tower, the sexton's strongroom."),
    Secret("crown-crab-pit", "The Crab Pit", "pen", "tide_cave", "crownwater-pavilion-pavilion_northeast", (-8.0, 8.0),
           creatures=(("bronze_tide_crab", 4), ("crystal_shore_crab", 3)),
           note="A tide pit the fishers stock with crab for the young to learn armour on."),
    Secret("crown-cathedral-school", "The Cathedral School", "school", "cracked_slab", "crownwater-cathedral", (-14.0, 8.0),
           texts=(("Reading", "The cathedral's under-room. Books read three times as fast under the stone."),
                  ("The grating", "The grating over the drowned court was found open. The diver says from below."),
                  ("Ferries", "Every quay serves a route; a second berth a few tiles along the dock serves the next. Read the stone before you step on the plank.")),
           note="Where the sexton teaches the choir their letters."),
    Secret("crown-warm-spring", "The Crown Spring", "spring", "tide_cave", "crownwater-pavilion-pavilion_west", (8.0, -8.0),
           note="A warm feed under the west pavilion; the lake is cold everywhere else."),
    Secret("crown-pavilion-butts", "The Pavilion Butts", "range", "drain_grate", "crownwater-pavilion-pavilion_north", (10.0, 8.0),
           creatures=(("river_otter", 3),),
           note="A long gallery under the north pavilion; otters at the far end, unbothered."),
    Secret("crown-court-reliquary", "The Sunken Court Reliquary", "reliquary", "shrine_slab", "crownwater-sunken-court", (10.0, 8.0), key="Shorebank Shell",
           texts=(("The crown", "The crown was drowned on purpose. The court was drowned by accident."),
                  ("The patina", "Deep patina takes a century. The patina on the grating hinge is a year old."),
                  ("The diver", "Teth-Sa dives the court every tenth day and comes up with nothing, on purpose.")),
           note="The court's own relic room, opened with a shell from the shore."),
    Secret("crown-cistern-well", "The Cistern Well", "nullwell", "drain_grate", "crownwater-customs-hall", (-10.0, -10.0),
           creatures=(("bronze_diving_beetle", 4),),
           note="The cistern's stones drink every spell; the beetles do not mind."),
    Secret("crown-lake-focus", "The Lake Focus", "focus", "cracked_slab", "crownwater-pavilion-pavilion_southeast", (8.0, 8.0), key="Iron Rune",
           note="A chamber under the islet where the lake's own ether pools."),
    Secret("crown-drain", "The Crown Drain", "tunnel", "drain_grate", "crownwater-pavilion-pavilion_east", (-12.0, -10.0),
           resources=(("Deep Lake Clay", 3), ("Mirror Reed", 3)),
           links=(("four_gates", "secret-gates-drain-mouth", "Up into the Four Gates"),),
           note="The old drain under the causeway, out under the city's west gate."),
    Secret("crown-waystone", "The Crown Waystone", "waystone", "cracked_slab", "crownwater-pavilion-pavilion_northwest", (8.0, 8.0), key="Iron Rune",
           links=(("mirrorhold_secrets", "mirror-waystone", "Mirrorhold"),
                  ("four_gates_secrets", "gates-waystone", "The Four Gates"),
                  ("manymouth_delta_secrets", "delta-waystone", "The Manymouth Delta"),
                  ("westhaven_secrets", "haven-waystone", "Westhaven"),
                  ("amethyst_barrens_secrets", "barrens-waystone", "The Amethyst Barrens"),
                  ("grey_moors_secrets", "moor-waystone", "The Grey Moors"),
                  ("ssarathi_ruins_secrets", "ruins-waystone", "The Ssarathi Ruins")),
           note="Seven stones for seven ferries. An iron rune wakes them."),
    Secret("crown-campanile-eyrie", "The Campanile Eyrie", "eyrie", "ivy_arch", "crownwater-campanile", (-10.0, -8.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Regeneration", "Sitting restores faster than standing; a spring restores faster than sitting.")),
           note="A pocket in the campanile's footing over the water."),
]
