"""The Manymouth Delta's secrets: what the silt keeps."""
from secretrooms import Secret

REGION = "manymouth_delta"
NAME = "Manymouth Delta Secrets"
PALETTE = {"floor": "packed_earth", "wall": "rubble_stone", "ceil": "timber_grey", "rock": "cliff_rock",
           "stone": "ashlar", "timber": "timber_grey", "water": "water_lagoon", "crystal": "blue_crystal",
           "node": "amber_resin", "turf": "verdant_fern_glade"}
PROP_PALETTE = {"rock": "cliff_rock", "bark": "bark_dark", "stone": "ashlar", "timber": "timber_grey",
                "reed": "thatch_reed", "dark": "bark_dark"}

SECRETS = [
    Secret("delta-lotus-hollow", "The Lotus Hollow", "grotto", "reed_hide", "great-banyan", (10.0, 8.0),
           resources=(("Delta Lotus", 5), ("Mangrove Sap", 4)),
           note="A hollow under the banyan's roots where the lotus opens out of the sun."),
    Secret("delta-paddy-garden", "The Paddy Garden", "garden", "reed_hide", "paddy-watchtower", (10.0, 8.0),
           resources=(("Riverflax", 4), ("Indigo Thistle", 4), ("Delta Lotus", 3), ("Tidewrack Kelp", 3)),
           area=("harvest_speed", 2),
           note="A sunken paddy under the tower where flax and thistle grow a step apart."),
    Secret("delta-market-cache", "The Market Cache", "cache", "cellar_hatch", None, (2.5, 2.5),
           door_map="manymouth_flooded_labyrinth", door_space="smugglers_warren.cache",
           resources=(("Mangrove Sap", 3), ("Indigo Thistle", 3)),
           note="The market's own cellar: a chest, a bench and the sap the dyers keep back."),
    Secret("delta-moot-vault", "The Moot Vault", "vault", "cracked_slab", "moot-hall", (10.0, 8.0), key="Storage Token",
           texts=(("The water lineage", "The stelae record the channels in the order they were claimed. What is made under the moot is recorded the same way, and counts double."),),
           note="The moot's strongroom above the flood line."),
    Secret("delta-crab-pit", "The Crab Pit", "pen", "reed_hide", "delta-overlook", (8.0, 8.0),
           creatures=(("delta_mud_crab", 4), ("mangrove_crab", 3)),
           note="A mud pit under the overlook where the young learn what armour is."),
    Secret("delta-study-school", "The Deck Study School", "school", "cellar_hatch", "deck-study", (8.0, 8.0),
           texts=(("Reading", "The study's under-deck. Books read three times as fast over the water."),
                  ("The lineage", "The tenth stela is blank. The scribe says the tenth channel was never claimed; the hermit says it was claimed twice."),
                  ("Silt", "The delta's centre is open water. The walkways are the roads; step off one and you swim.")),
           note="Where the stelae court's scribes learn the order of the channels."),
    Secret("delta-temple-spring", "The Green Temple Spring", "spring", "loose_stone", "green-temple", (-10.0, 8.0),
           note="A warm feed under the temple; the silt around it never sets."),
    Secret("delta-watch-butts", "The East Watch Butts", "range", "cellar_hatch", "east-watch", (-8.0, 8.0),
           creatures=(("swamp_heron", 3),),
           note="A gallery under the watch with herons at the far end that will not fly."),
    Secret("delta-stelae-reliquary", "The Stelae Reliquary", "reliquary", "shrine_slab", "stelae-court", (12.0, 8.0), key="Shorebank Shell",
           texts=(("The ruling", "The ruling under rebuke still stands. Nobody has moved to rebuke the rebuke."),
                  ("Verification", "Verification of the lineage lapsed in the year the tenth stone was cut blank."),
                  ("The labyrinth", "The flooded labyrinth was a granary before the water came, and the water was let in.")),
           note="The court's relic room, opened with a shell."),
    Secret("delta-shrine-well", "The South Shrine Well", "nullwell", "cracked_slab", "south-shrine", (8.0, 8.0),
           creatures=(("delta_mud_crab", 4),),
           note="The shrine's cistern swallows spells; the crabs penned there are indifferent."),
    Secret("delta-arch-focus", "The Great Arch Focus", "focus", "reed_hide", "great-arch", (10.0, 8.0), key="Iron Rune",
           note="Under the great arch the ether pools; spells cost half."),
    Secret("delta-bund-run", "The Bund-Run", "tunnel", "reed_hide", "paddy-watchtower", (-10.0, -8.0),
           resources=(("Riverflax", 3), ("Moor Peat", 3)),
           links=(("grey_moors", "secret-moor-bund-mouth", "Up onto the Grey Moors"),),
           note="A drain the bund wardens drove under the border, out onto the moor."),
    Secret("delta-waystone", "The Delta Waystone", "waystone", "cracked_slab", "labyrinth-mouth", (10.0, -8.0), key="Iron Rune",
           links=(("crownwater_secrets", "crown-waystone", "Crownwater"),
                  ("ssarathi_ruins_secrets", "ruins-waystone", "The Ssarathi Ruins"),
                  ("grey_moors_secrets", "moor-waystone", "The Grey Moors"),
                  ("westhaven_secrets", "haven-waystone", "Westhaven")),
           note="Four stones by the labyrinth mouth. An iron rune wakes them."),
    Secret("delta-banyan-eyrie", "The Banyan Eyrie", "eyrie", "ivy_arch", "great-banyan", (-10.0, -8.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Mixing", "A field station mixes what a bench mixes. Two ingredients a step apart is what a garden is for.")),
           note="A pocket in the banyan's crown."),
    Secret("delta-rootrun-mouth", "The Root-Run Mouth", "mouth", "root_door", "great-banyan", (12.0, -10.0),
           links=(("ssarathi_ruins_secrets", "ruins-rootrun-far", "Down the root-run to the Ssarathi Ruins"),),
           note="Where the ruins' root-run comes up in the delta."),
]
