"""The Verdant Stair's secrets: what the terraces keep behind the vines."""
from secretrooms import Secret

REGION = "verdant_stair"
NAME = "Verdant Stair Secrets"
PALETTE = {"floor": "verdant_jungle_floor", "wall": "verdant_wet_limestone", "ceil": "verdant_limestone_cliff",
           "rock": "verdant_limestone_cliff", "stone": "verdant_terrace_stone", "timber": "timber_dark",
           "water": "water_cenote", "crystal": "verdant_jade", "node": "verdant_frond", "turf": "verdant_fern_glade"}
PROP_PALETTE = {"rock": "verdant_limestone_cliff", "bark": "bark_dark", "stone": "verdant_terrace_stone",
                "timber": "timber_dark", "dark": "bark_dark"}

SECRETS = [
    Secret("stair-cenote-hollow", "The Cenote Hollow", "grotto", "ivy_arch", "cenote", (12.0, 8.0),
           resources=(("Cenote Watercress", 5), ("Verdant Venom Bulb", 3)),
           note="A side-hollow of the cenote where the cress grows thick and the bulbs are left alone."),
    Secret("stair-hanging-garden", "The Under-Garden", "garden", "ivy_arch", "hanging-gardens", (10.0, 8.0),
           resources=(("Lavender", 4), ("Indigo Thistle", 4), ("Mangrove Sap", 3), ("Cenote Watercress", 3)),
           area=("harvest_speed", 2),
           note="The hanging gardens' cellar terrace, where the gardeners grow what the tourists do not see."),
    Secret("stair-provisioner-cache", "The Provisioner's Cache", "cache", "cellar_hatch", None, (2.5, 2.0),
           door_map="verdant_stair_insides", door_space="stair_quarry.sorting",
           resources=(("Verdant Venom Bulb", 2), ("Lavender", 3)),
           note="The provisioner's cellar: a chest, a bench and the bulbs off the books."),
    Secret("stair-temple-vault", "The Great Temple Vault", "vault", "cracked_slab", "great-temple", (14.0, 8.0), key="Storage Token",
           texts=(("The stair's slope", "The anchor stone moved and the stair kept its slope. What is made under the temple is counted twice, once for the work and once for the climb."),),
           note="The temple's strongroom, under the processional."),
    Secret("stair-quarry-pit", "The Quarry Pit", "pen", "loose_stone", "quarry", (-10.0, 8.0),
           creatures=(("canopy_glider", 4), ("leafwing_owl", 3)),
           note="A quarry cell the stair-house stocks with gliders for the young to learn the air on."),
    Secret("stair-house-school", "The Stair-House School", "school", "cracked_slab", "stair-house", (10.0, 8.0),
           texts=(("Reading", "The stair-house's under-room. Books read three times as fast."),
                  ("The anchor", "The anchor stone was moved a few metres upslope. The rigger says the ropes were re-run the same night."),
                  ("The nine lost", "Nine were lost on the stair in one season, and the coal price doubled the next.")),
           note="Where the stair wardens learn the stair."),
    Secret("stair-water-spring", "The Water Shrine Spring", "spring", "loose_stone", "water-shrine", (-10.0, 8.0),
           note="The shrine's warm feed, in a chamber behind the basin."),
    Secret("stair-lookout-butts", "The East Lookout Butts", "range", "cellar_hatch", "east-lookout", (8.0, 8.0),
           creatures=(("swamp_heron", 3),),
           note="A gallery under the lookout with herons at the far end."),
    Secret("stair-ridge-reliquary", "The Ridge Shrine Reliquary", "reliquary", "shrine_slab", "ridge-shrine", (10.0, 8.0), key="Bright Feather",
           texts=(("The bulb bed", "The physick's bulb bed is where the venom bulbs are grown, not gathered. Nobody says so."),
                  ("The socket", "The anchor's empty socket still takes rain. The stair drains toward it."),
                  ("The summit", "The summit watch was built to watch the stair, not the sky.")),
           note="Opened with a feather from the canopy."),
    Secret("stair-cenote-well", "The Cenote Well", "nullwell", "loose_stone", "cenote", (-12.0, -8.0),
           creatures=(("moonshadow_lynx", 2),),
           note="Limestone drinks every spell here; the lynx penned below does not need one."),
    Secret("stair-sun-focus", "The Sun Pavilion Focus", "focus", "cracked_slab", "sun-pavilion", (10.0, 8.0), key="Iron Rune",
           note="Under the sun pavilion the ether pools; spells cost half."),
    Secret("stair-culvert", "The Culvert", "tunnel", "ivy_arch", "boundary-shrine", (-10.0, 8.0),
           resources=(("Cenote Watercress", 3), ("Ssarathi Scale Moss", 3)),
           links=(("ssarathi_ruins", "secret-ruins-culvert-mouth", "Down into the Ssarathi Ruins"),),
           note="An aqueduct culvert under the border, out into the ruins."),
    Secret("stair-waystone", "The Stair Waystone", "waystone", "cracked_slab", "upper-court", (10.0, 8.0), key="Iron Rune",
           links=(("sunmane_steppe_secrets", "steppe-waystone", "The Sunmane Steppe"),
                  ("ssarathi_ruins_secrets", "ruins-waystone", "The Ssarathi Ruins")),
           note="Two stones under the upper court. An iron rune wakes them."),
    Secret("stair-summit-eyrie", "The Summit Eyrie", "eyrie", "ivy_arch", "summit-watch", (8.0, 8.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Climbing", "A rope crossing carries you where the walk grid says it does. If the deck is not walkable on the server you will not be let onto it.")),
           note="A pocket under the summit watch."),
]
