"""The Amethyst Barrens' secrets: what the Glasswardens keep under the dust."""
from secretrooms import Secret

REGION = "amethyst_barrens"
NAME = "Amethyst Barrens Secrets"
PALETTE = {"floor": "amethyst_vault_floor", "wall": "amethyst_storm_rock", "ceil": "amethyst_storm_rock",
           "rock": "amethyst_storm_rock", "stone": "amethyst_pale_stone", "timber": "timber_dark",
           "water": "water_pool", "crystal": "amethyst_crystal", "node": "amethyst_crystal",
           "turf": "amethyst_barrens_dust"}
PROP_PALETTE = {"rock": "amethyst_storm_rock", "bark": "bark_dark", "stone": "amethyst_pale_stone",
                "timber": "timber_dark", "crystal": "amethyst_crystal"}

SECRETS = [
    Secret("barrens-geode-hollow", "The Geode Hollow", "grotto", "crystal_seam", "amethyst-geode-cave-1", (10.0, 6.0),
           resources=(("Resonant Crystal", 4), ("Voltaic Geode", 3), ("Pale Quartz", 3)),
           note="A geode the prospectors never finished: crystal on every wall and a pool of dust."),
    Secret("barrens-shard-garden", "The Shard Garden", "garden", "crystal_seam", "resonant-crystal-cluster-3", (8.0, 8.0),
           resources=(("Stormglass Shard", 4), ("Sulfur", 3), ("Quartz", 3), ("Pale Quartz", 3)),
           area=("harvest_speed", 2),
           note="Shards grown in beds under a lid of storm rock, faster than the open field."),
    Secret("barrens-station-cache", "The Field Station Cache", "cache", "cellar_hatch", "glasswarden-field-station-1", (6.0, 6.0),
           resources=(("Stormglass Shard", 3), ("Resonant Crystal", 2)),
           note="The station's cellar: a chest, a bench and the shards the wardens sort in private."),
    Secret("barrens-observatory-vault", "The Observatory Vault", "vault", "cracked_slab", "glasswarden-observatory", (14.0, 8.0), key="Storage Token",
           texts=(("The factor's signature", "The Barrens factor signs for a shard once. What is made under the observatory is checked against the eleven measures and counts double."),),
           note="The wardens' strongroom under the observatory."),
    Secret("barrens-beetle-pit", "The Beetle Pit", "pen", "loose_stone", "amethyst-storm-ruin-0", (10.0, -6.0),
           creatures=(("crystal_carapace_beetle", 4), ("crystal_mite", 4)),
           note="A storm-ruin cellar the wardens stock with beetles for the young to break their shields on."),
    Secret("barrens-tower-school", "The Tower School", "school", "cracked_slab", "glasswarden-tower-2", (8.0, 6.0),
           texts=(("Reading", "The tower's under-room; the wardens taught here before the observatory. Books read three times as fast."),
                  ("Tuning", "A shard is tuned by walking it past all eleven measures. Eleven collars, eleven lengths, no shortcuts."),
                  ("The massif", "The massif hums on the day before a storm. Count the hum and you know the hour.")),
           note="Where the wardens learn to read a resonance chart."),
    Secret("barrens-resonance-spring", "The Resonance Spring", "spring", "crystal_seam", "resonance-ring", (0.0, 12.0),
           note="Under the ring the water hums, and wounds close to the hum."),
    Secret("barrens-bridge-butts", "The Bridge Butts", "range", "cellar_hatch", "amethyst-crystal-bridge-4", (-8.0, 8.0),
           creatures=(("amethyst_scorpion", 3),),
           note="A gallery under the crystal bridge; scorpions at the far end for slow shots."),
    Secret("barrens-massif-reliquary", "The Massif Reliquary", "reliquary", "shrine_slab", "the-amethyst-massif", (12.0, 10.0), key="Resonant Crystal",
           texts=(("The eleven measures", "The measures were cut from one crystal. The twelfth length was never set; the factor knows why."),
                  ("The storm ruins", "The ruins were not storm-broken. They were struck, once each, on the same night."),
                  ("The vault", "The Resonant Vault under the observatory was a mine before it was a vault.")),
           note="Sealed with a resonant crystal; the massif's own relic room."),
    Secret("barrens-storm-well", "The Storm Well", "nullwell", "cracked_slab", "amethyst-storm-ruin-3", (8.0, 8.0),
           creatures=(("crystal_cave_spider", 3),),
           note="Storm rock swallows spells. The spiders penned here never learnt that."),
    Secret("barrens-lens-focus", "The Shard Focus", "focus", "crystal_seam", None, (4.0, 3.0), key="Iron Rune",
           door_map="resonant_vault", door_space="resonant_vault.lens",
           note="Where the shards hang the ether pools; spells cost half."),
    Secret("barrens-sap", "The Sap", "tunnel", "sand_sink", "amethyst-storm-ruin-3", (-12.0, 12.0),
           resources=(("Sulfur", 3), ("Sunstone Flint", 3)),
           links=(("sunmane_steppe", "secret-steppe-sap-mouth", "Up onto the Sunmane Steppe"),),
           note="A sap the wardens drove south under the dust, out onto the steppe."),
    Secret("barrens-waystone", "The Barrens Waystone", "waystone", "cracked_slab", "glasswarden-field-station-3", (-10.0, 8.0), key="Iron Rune",
           links=(("whitehorn_range_secrets", "horn-waystone", "The Whitehorn Range"),
                  ("mirrorhold_secrets", "mirror-waystone", "Mirrorhold"),
                  ("sunmane_steppe_secrets", "steppe-waystone", "The Sunmane Steppe"),
                  ("crownwater_secrets", "crown-waystone", "Crownwater")),
           note="Four stones under the field station. An iron rune wakes them."),
    Secret("barrens-cave-eyrie", "The Geode Eyrie", "eyrie", "crystal_seam", "amethyst-geode-cave-2", (10.0, -6.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Harvest", "A pickaxe in the pack or in the hand is the same to a seam. A seam above your level takes ten times as long, not twice.")),
           note="A crystal pocket over the cave mouth."),
]
