extends Node
## Plays Eloria's sounds in answer to what the server said happened.
##
## The client had no audio at all. Everything here is triggered by an
## authoritative event - a harvest the server started, an item it put in the
## backpack, a combat outcome it reported, an effect it announced - or by the
## player's own click on a control. Nothing is played on a guess, and nothing
## is played twice for one event: a repeated snapshot that says the same thing
## is not a new event.
##
## Every sound is generated by `eloria-assets/tools/build_native_sounds.py`
## from noise and sine partials. Nothing is sampled or converted.
##
## The script declares no `class_name`: a global class is parsed before the
## autoload singletons are registered, and this reads `AppState` directly.

const CATALOG_PATH := "res://assets/audio/catalog.json"
const AUDIO_DIRECTORY := "res://assets/audio/"
## Enough voices for a busy moment without letting one event drown the rest.
const VOICE_COUNT := 8
## The floor between two steps. The server can restate several movement
## commands in one frame; that is one step, not four.
const STEP_INTERVAL_MSEC := 180

var enabled := true:
	set(value):
		enabled = value
		if not value:
			stop_all()
var volume_linear := 0.7:
	set(value):
		volume_linear = clampf(value, 0.0, 1.0)
		for player: AudioStreamPlayer in _voices:
			player.volume_db = linear_to_db(maxf(0.0001, volume_linear))

var _streams: Dictionary = {}
var _voices: Array[AudioStreamPlayer] = []
var _next_voice := 0
## What the last authoritative snapshot said, so a restatement is not an event.
var _harvesting := false
var _combat_event := -1
var _inventory_totals: Dictionary = {}
## Where the server last said the player was standing, so a step is heard when
## the tile changes rather than on every actor packet.
var _local_tile := Vector2i(-1, -1)
var _last_step_msec := 0

func _ready() -> void:
	name = "AudioDirector"
	_load_catalog()
	for index: int in range(VOICE_COUNT):
		var player := AudioStreamPlayer.new()
		player.name = "Voice%d" % index
		player.volume_db = linear_to_db(maxf(0.0001, volume_linear))
		add_child(player)
		_voices.append(player)
	AppState.state_changed.connect(_on_state_changed)
	AppState.special_effect_requested.connect(_on_special_effect)

## The sounds this client knows about, by name.
func sound_names() -> Array[String]:
	var names: Array[String] = []
	for key: Variant in _streams:
		names.append(str(key))
	names.sort()
	return names

## Plays one sound by name. Returns false when audio is off or the name is not
## in the catalog, so a caller can be tested without listening.
func play(name: String) -> bool:
	if not enabled or not _streams.has(name):
		return false
	var player: AudioStreamPlayer = _voices[_next_voice]
	_next_voice = (_next_voice + 1) % _voices.size()
	player.stream = _streams[name] as AudioStream
	player.play()
	return true

func stop_all() -> void:
	for player: AudioStreamPlayer in _voices:
		player.stop()

## True while any voice is sounding. Used by the tests rather than by the game.
func is_playing() -> bool:
	for player: AudioStreamPlayer in _voices:
		if player.playing:
			return true
	return false

func _load_catalog() -> void:
	var file := FileAccess.open(CATALOG_PATH, FileAccess.READ)
	if file == null:
		return
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	if not parsed is Dictionary:
		return
	for raw_sound: Variant in (parsed as Dictionary).get("sounds", []):
		var sound: Dictionary = raw_sound as Dictionary
		var stream: Resource = load(
			AUDIO_DIRECTORY + str(sound.get("file", "")))
		if stream is AudioStream:
			_streams[str(sound.get("name", ""))] = stream as AudioStream

func _on_state_changed(path: StringName) -> void:
	match path:
		&"harvest":
			var harvesting: bool = bool(AppState.harvest.get("active", false))
			if harvesting and not _harvesting:
				play("harvest_start")
			_harvesting = harvesting
		&"actors", &"local_actor":
			_on_local_actor_moved()
		&"inventory":
			_on_inventory_changed()
		&"combat_state":
			_on_combat_changed()
		&"connection":
			if AppState.connection_state == "disconnected":
				_harvesting = false
				_combat_event = -1
				_local_tile = Vector2i(-1, -1)
				_inventory_totals.clear()
				stop_all()

## A backpack that gained something makes the gathering sound. The comparison
## is against the previous authoritative snapshot, so a restatement that
## changes nothing is silent.
func _on_inventory_changed() -> void:
	var totals: Dictionary = {}
	var gained := false
	for raw_slot: Variant in AppState.inventory:
		var item: Dictionary = AppState.inventory[raw_slot] as Dictionary
		var image_id: int = int(item.get("image_id", 0))
		var quantity: int = int(item.get("quantity", 0))
		totals[image_id] = int(totals.get(image_id, 0)) + quantity
		if quantity > int(_inventory_totals.get(image_id, 0)):
			gained = true
	if gained and not _inventory_totals.is_empty():
		play("harvest_gather" if _harvesting else "item_pickup")
	_inventory_totals = totals

## A step is heard when the server says the player is standing somewhere else.
## The first tile after login is not a step - the player did not walk there -
## and a burst of movement commands in one frame is still one step.
func _on_local_actor_moved() -> void:
	var actor: Variant = AppState.actors.get(AppState.local_actor_id)
	if actor is not Dictionary:
		return
	var tile := Vector2i(int((actor as Dictionary).get("x", 0)),
		int((actor as Dictionary).get("y", 0)))
	if tile == _local_tile:
		return
	var first_sighting: bool = _local_tile == Vector2i(-1, -1)
	_local_tile = tile
	var now: int = Time.get_ticks_msec()
	if first_sighting or now - _last_step_msec < STEP_INTERVAL_MSEC:
		return
	_last_step_msec = now
	play("footstep")

func _on_combat_changed() -> void:
	var event: int = int(AppState.combat_state.get("event", 0))
	if event == _combat_event:
		return
	_combat_event = event
	match event:
		EloriaProtocol.COMBAT_EVENT_HIT:
			play("combat_hit")
		EloriaProtocol.COMBAT_EVENT_MISS, EloriaProtocol.COMBAT_EVENT_DODGE:
			play("combat_miss")

func _on_special_effect(_effect: Dictionary) -> void:
	play("world_effect")
