#!/usr/bin/env python3
"""Generate v2 registry rows from the active catalog's source or served packages.

Use --preview during bootstrap; a served package cannot be downgraded to preview.
Default mode requires every package and promotes all catalog entries together.
Only explicitly retired partition IDs are removed; legacy rows are preserved.
--check compares generated bytes and writes nothing.
"""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
import sys

import frames as F


def read(path):
    return json.loads(path.read_text(encoding="utf-8"))


def build(checkout, *, preview=False):
    checkout = Path(checkout)
    registry = read(checkout / F.REGISTRY)
    rows = registry["maps"]
    catalog = read(checkout / F.CATALOG)
    partition = read(F._res(catalog["partitionSpecPath"], checkout))
    active = set(F.regions(checkout))
    retired = set(partition["retiredMapIds"])
    if active & retired:
        raise ValueError("the active catalog still contains retired map IDs")
    unexpected = [region for region, row in rows.items()
                  if row.get("status") == "continent-v2-served" and region not in active | retired]
    if unexpected:
        raise ValueError(f"unexpected served v2 rows outside the partition: {unexpected}")
    for region in retired:
        rows.pop(region, None)
    for entry in F.catalog_entries(checkout):
        region = entry["id"]
        stub = read(F._res(entry["manifestPath"], checkout))
        server = stub["server"]
        package_path = F._res(entry["publishedManifestPath"], checkout)
        package = read(package_path) if package_path.is_file() else None
        if preview:
            if package and (package.get("collision") or {}).get("servedGrid"):
                raise ValueError(f"{region}: a served package cannot become a preview")
            ox, oy = server["origin"]
            width, height = server["cells"]
            coordinate = {"metresPerTile": 1.0, "serverOrigin": [ox, oy], "serverCells": [width, height],
                          "origin": [0, 0, 0], "walkingHeight": 0.0, "invertServerY": True,
                          "serverStorageVersion": 1, "serverTileMin": [0, 0],
                          "addressableWorldBounds": {"min": [-ox, oy-height], "max": [width-ox, oy]}}
            geography = copy.deepcopy(stub["continentGeography"])
        else:
            if not package or not (package.get("collision") or {}).get("servedGrid"):
                raise ValueError(f"{region}: publish its served package before registry promotion")
            coordinate = copy.deepcopy(package["coordinateTransform"])
            geography = copy.deepcopy(package["continentGeography"])
            if (coordinate["serverOrigin"] != server["origin"] or coordinate["serverCells"] != server["cells"]
                    or geography["translation"] != stub["continentGeography"]["translation"]):
                raise ValueError(f"{region}: served package differs from its source frame")
            for field in ("ownershipPolygon", "ownershipPolygons"):
                if geography.get(field) != stub["continentGeography"].get(field):
                    raise ValueError(f"{region}: served ownership differs from its source")
        geography.update(frame="continent-v2", serverCells=server["cells"],
                         serverStorageVersion=1, serverTileMin=[0, 0])
        rows[region] = {"manifest": entry["publishedManifestPath"], "label": entry["label"],
                        "coordinateTransform": coordinate,
                        "status": "continent-v2-client-preview" if preview else "continent-v2-served",
                        "landscapeTransitions": not preview, "continentGeography": geography}
    return (json.dumps(registry, indent=2, ensure_ascii=False, allow_nan=False) + "\n").encode("utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkout", type=Path, default=F.DEFAULT_CHECKOUT)
    parser.add_argument("--preview", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        for region in F.regions(args.checkout):
            F.load_source(region, args.checkout)
        blob = build(args.checkout, preview=args.preview)
        path = args.checkout / F.REGISTRY
        if args.check:
            if path.read_bytes() != blob:
                raise ValueError("registry rows are stale; run publish_registry.py")
        else:
            path.write_bytes(blob)
        for region in F.regions(args.checkout):
            (F.load_source if args.preview else F.load)(region, args.checkout)
    except (OSError, ValueError, KeyError) as error:
        print(f"publish_registry: {error}", file=sys.stderr)
        return 1
    print(json.dumps({"mode": "preview" if args.preview else "served", "maps": F.regions(args.checkout)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
