#!/usr/bin/env python3
"""Reconcile the server's item table with the sixty-four leg garment visuals.

Nothing else reconciles them.  A leg garment exists on the client as a visual id
in `equipment.json` and on the server as an `[item]` block in `config/items.txt`,
and the only thing joining the two is `EQUIPMENT_VISUAL_OVERRIDES` in
`eloria/items.py`.  A design present in one and absent from the other is either
an item nobody can see or a mesh nobody can wear, and neither fails loudly.

Every design is a **new item**, not a re-skin and not a tint.  The generic tier
already carries the tint case - nine colours of `generic_pants` behind visuals
4:0-4:8 - and these sixty-four are distinct silhouettes with distinct feature
sets, so collapsing any of them onto a shared item would throw away the thing
that makes it worth authoring.

Item ids continue from the end of the existing table.  Icons reuse the existing
inventory art for the nearest equivalent: the inventory atlas is a separate
pipeline that this brief does not cover, and inventing image ids that resolve to
nothing would put an empty square in every player's bag.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

from legwear_pieces import LEGWEAR_EQUIPMENT
from legwear_roster import ROSTER

#: Inventory icons already in the atlas, chosen per finish.
ICON = {"plate": 358, "mail": 179, "crystal": 363, "leather": 137,
        "cloth": 532, "fur": 213, "wood": 137, "shell": 418}

#: Armour rating and weight per kind.  Soft trousers protect little and weigh
#: little; plate is the other way round.  The ranges deliberately sit inside the
#: existing ladder rather than above it - these are new designs, not new tiers,
#: and a sixty-four-piece set that outclasses titanium would rewrite the economy.
STATS = {
    "pants": {"armor": "1/2", "emu": 6, "category": "Clothes"},
    "legs": {"armor": "2/5", "emu": 15, "category": "Armor"},
    "kilt": {"armor": "1/3", "emu": 9, "category": "Clothes"},
}

#: Which sheet a design came from, for the description line.
SHEET_NOTE = {
    "legendary": "A relic of the elder wars, kept bright by more than polish.",
    "arcane": "Woven where the tide and the star-road meet.",
    "amberwood": "Grown as much as made, in the deep Amberwood.",
    "sunmane": "Cut for long riding across the Sunmane steppe.",
    "ceremonial": "Parade harness of a knightly order.",
    "militia": "Issued kit, mended more often than replaced.",
    "ranger": "Worn soft by years of walking the marches.",
    "frontier": "Honest cloth, patched at the knee.",
}

BLOCK = """[item]
name: {name}
item_id: {item_id}
image_id: {image_id}
emu: {emu}
flags: 2
category: {category}
equip_type: legs
description: {description}
armor: {armor}
damage: 0/0
accuracy: 0
defense: 0
cold_damage: 0
heat_damage: 0
radiation_damage: 0
magic_damage: 0
magic_resistance: 0
magic_protection: {magic_protection}
cold_protection: {cold_protection}
heat_protection: 0
radiation_protection: 0
critical_to_hit: 0
critical_to_damage: 0
light_modifier: 0
perception_bonus: 0
missile_accuracy: 0
archery_ap: 0
missile_protection: 0
max_health: 0
max_ether: 0
[/item]
"""


def next_item_id(items_txt: str) -> int:
    ids = [int(m) for m in re.findall(r"^item_id: (\d+)", items_txt, re.M)]
    return max(ids) + 1


def existing_names(items_txt: str) -> set[str]:
    return {m.strip().casefold()
            for m in re.findall(r"^name: (.+)$", items_txt, re.M)}


def blocks(items_txt: str) -> tuple[str, dict[str, tuple[int, int]]]:
    """The new `[item]` blocks, and the name -> (part, visual) they need."""
    kinds = {slug: kind for slug, _n, _s, _t, kind, _f in ROSTER}
    sheets = {slug: sheet for slug, _n, sheet, _t, _k, _f in ROSTER}
    taken = existing_names(items_txt)
    item_id = next_item_id(items_txt)
    out, overrides = [], {}
    for slug, label, part, visual, kind, _base, _accent, _feats, finish in LEGWEAR_EQUIPMENT:
        if label.casefold() in taken:
            raise SystemExit(f"item name already in the table: {label}")
        stats = STATS[kind]
        out.append(BLOCK.format(
            name=label, item_id=item_id, image_id=ICON[finish],
            emu=stats["emu"], category=stats["category"],
            description=SHEET_NOTE[sheets[slug]],
            armor=stats["armor"],
            magic_protection=1 if finish == "crystal" else 0,
            cold_protection=2 if finish == "fur" else 0))
        overrides[label.casefold()] = (part, visual)
        item_id += 1
    return "\n".join(out), overrides


def overrides_source(overrides: dict[str, tuple[int, int]]) -> str:
    lines = ["    # The sixty-four rebuilt leg garments, part 4 visuals 16-79.",
             "    # Generated by eloria-assets/tools/legwear_server_items.py; the",
             "    # client half of the pair is legwear_pieces.LEGWEAR_EQUIPMENT.",
             "    # Nothing else joins an item name to the mesh a player sees."]
    for name, (part, visual) in overrides.items():
        lines.append(f'    "{name}": ({part}, {visual}),')
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--server", type=Path, required=True,
                        help="the eloria-server checkout to reconcile")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    items_path = args.server / "config" / "items.txt"
    py_path = args.server / "eloria" / "items.py"
    items_txt = items_path.read_text(encoding="utf-8", errors="replace")
    new_blocks, overrides = blocks(items_txt)
    source = py_path.read_text(encoding="utf-8")
    anchor = "EQUIPMENT_VISUAL_OVERRIDES: dict[str, tuple[int, int]] = {\n"
    if "The sixty-four rebuilt leg garments" in source:
        raise SystemExit("overrides already present; nothing to do")
    if not args.write:
        print(f"{len(overrides)} items, ids "
              f"{next_item_id(items_txt)}-{next_item_id(items_txt) + 63}")
        print(new_blocks[:400])
        return
    items_path.write_text(items_txt.rstrip("\n") + "\n\n" + new_blocks,
                          encoding="utf-8")
    py_path.write_text(source.replace(
        anchor, anchor + overrides_source(overrides) + "\n", 1), encoding="utf-8")
    print(f"wrote {len(overrides)} items and their visual overrides")


if __name__ == "__main__":
    main()
