"""The Grey Moors' secrets: what the peat keeps."""
from secretrooms import Secret

REGION = "grey_moors"
NAME = "Grey Moors Secrets"
PALETTE = {"floor": "grey_moor_track", "wall": "grey_drystone", "ceil": "grey_bog_timber", "rock": "grey_moor_granite",
           "stone": "grey_carved_stone", "timber": "grey_bog_timber", "water": "grey_bog_water",
           "crystal": "grey_wisp", "node": "grey_votive_flame", "turf": "grey_heather_moor"}
PROP_PALETTE = {"rock": "grey_moor_granite", "bark": "grey_dead_bark", "stone": "grey_drystone",
                "timber": "grey_bog_timber"}

SECRETS = [
    Secret("moor-peat-hollow", "The Peat Hollow", "grotto", "cairn", "grey-peat-working-2", (10.0, 8.0),
           resources=(("Moor Peat", 5), ("Bog Iron Nodule", 4)),
           note="A cutting the peat men roofed over: dry peat and bog iron in the same wall."),
    Secret("moor-croft-garden", "The Croft Garden", "garden", "cellar_hatch", "grey-croft-1", (10.0, 6.0),
           resources=(("Moorcotton", 4), ("Barrow Bramble", 4), ("Grave Moss", 3), ("Moor Peat", 3)),
           area=("harvest_speed", 2),
           note="A croft's sunken garden where cotton and bramble grow out of the wind."),
    Secret("moor-boardwalk-cache", "The Boardwalk Cache", "cache", "reed_hide", "grey-boardwalk-1", (8.0, 6.0),
           resources=(("Bog Iron Nodule", 3), ("Grave Moss", 3)),
           note="A dry cell under the boardwalk: chest, bench and the nodules the smith hides from the reader."),
    Secret("moor-court-vault", "The Barrow Court Vault", "vault", "cracked_slab", "grey-barrow-court", (14.0, 6.0), key="Storage Token",
           texts=(("The barrow debt", "Eleven breached, eleven return fields left blank. What is made over the court is entered against the debt and counts double."),),
           note="The court's strongroom, under the great barrow's kerb."),
    Secret("moor-hound-pit", "The Hound Pit", "pen", "loose_stone", "grey-tower-5", (8.0, 8.0),
           creatures=(("mossbound_hound", 4), ("moss_armored_hound", 3)),
           note="A tower cellar where the wardens pen hounds for the young to learn on."),
    Secret("moor-shrine-school", "The Moor Shrine School", "school", "cracked_slab", "grey-shrine-1", (8.0, 8.0),
           texts=(("Reading", "The shrine's under-room. Books read three times as fast in the peat-quiet."),
                  ("The debt", "A debt-reader reads a barrow's kerb the way a clerk reads a ledger. The eleventh kerb has a stone missing."),
                  ("Bog iron", "Bog iron is harvested with nothing but hands; it is the smelting that wants the pickaxe.")),
           note="Where the debt-readers learn to read kerbs."),
    Secret("moor-hanged-spring", "The Hanged Oak Spring", "spring", "hollow_tree", "grey-hanged-oak", (8.0, 6.0),
           note="Under the hanged oak a warm seep the moor never froze; wounds close to it."),
    Secret("moor-ring-butts", "The Stone Ring Butts", "range", "cairn", "grey-stone-ring-4", (10.0, 8.0),
           creatures=(("moor_pony", 3),),
           note="A gallery under the ring; ponies at the far end for slow shots."),
    Secret("moor-crypt-reliquary", "The West Crypt Reliquary", "reliquary", "shrine_slab", None, (3.0, 3.0), key="Bones",
           door_map="grey_moor_barrows", door_space="bone_gallery.gallery",
           texts=(("The eleven", "Eleven barrows breached in one winter, and nothing taken from any of them but the kerb stones."),
                  ("The fifth chamber", "The fifth chamber is a false barrow: built empty, sealed full."),
                  ("The blank fields", "A blank return field is not a debt unpaid. It is a debt nobody will name.")),
           note="Opened with bones, as the crypts are."),
    Secret("moor-barrow-well", "The Barrow Well", "nullwell", "cairn", "grey-barrow-1", (10.0, 8.0),
           creatures=(("briarhide_wolf", 3),),
           note="Granite and peat swallow every spell here; the wolves penned below never needed one."),
    Secret("moor-wisp-focus", "The Wisp Focus", "focus", "cairn", "grey-stone-ring-2", (8.0, 8.0), key="Woven Charm",
           note="Where the wisps gather the ether pools; spells cost half."),
    Secret("moor-peatcut", "The Peat-Cut", "tunnel", "reed_hide", "grey-peat-working-3", (8.0, 8.0),
           resources=(("Moor Peat", 3), ("Moorcotton", 3)),
           links=(("westhaven", "secret-haven-peatcut-mouth", "Up into Westhaven"),),
           note="The peat men's cut under the border, out onto Westhaven's upland."),
    Secret("moor-waystone", "The Moor Waystone", "waystone", "cairn", "grey-stone-ring-0", (0.0, 12.0), key="Iron Rune",
           links=(("westhaven_secrets", "haven-waystone", "Westhaven"),
                  ("crownwater_secrets", "crown-waystone", "Crownwater"),
                  ("amberwood_secrets", "amber-waystone", "Amberwood"),
                  ("manymouth_delta_secrets", "delta-waystone", "The Manymouth Delta")),
           note="Four stones under the ring. An iron rune wakes them."),
    Secret("moor-tower-eyrie", "The Tower Eyrie", "eyrie", "ivy_arch", "grey-tower-3", (8.0, 8.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Daily work", "Mora Fen's ghost orchids grow in one patch on this moor. A task names the patch; look for the flowers, not the tile.")),
           note="A pocket in the east tower's footing."),
    Secret("moor-undercut-mouth", "The Undercut Mouth", "mouth", "root_door", "grey-dead-tree-6", (8.0, 6.0),
           links=(("amberwood_secrets", "amber-undercut-far", "Down the undercut to Amberwood"),),
           note="Where Amberwood's charcoal tunnel comes up on the moor."),
    Secret("moor-bund-mouth", "The Bund-Run Mouth", "mouth", "reed_hide", "grey-boardwalk-5", (8.0, 8.0),
           links=(("manymouth_delta_secrets", "delta-bund-run-far", "Down the bund-run to the Manymouth Delta"),),
           note="Where the delta's bund-run comes up on the moor."),
]
