"""Mirrorhold's secrets: what the city of lenses keeps behind its glass."""
from secretrooms import Secret

REGION = "mirrorhold"
NAME = "Mirrorhold Secrets"
PALETTE = {"floor": "pale_ashlar", "wall": "veined_marble", "ceil": "veined_marble", "rock": "cliff_rock",
           "stone": "pale_ashlar", "timber": "timber_dark", "water": "water_lake", "crystal": "mirror_glass",
           "node": "blue_crystal", "turf": "alpine_turf"}
PROP_PALETTE = {"rock": "cliff_rock", "bark": "bark_dark", "stone": "pale_ashlar", "timber": "timber_dark"}

SECRETS = [
    Secret("mirror-reed-cut", "The Reed Cut", "grotto", "reed_hide", "lake-north", (10.0, -6.0),
           resources=(("Mirror Reed", 5), ("Deep Lake Clay", 4)),
           note="A cut in the lake bank where the reed grows out of the wind and the clay is clean."),
    Secret("mirror-lens-garden", "The Lens-Grinders' Garden", "garden", "drain_grate", "lens-works", (12.0, 6.0),
           resources=(("Pale Quartz", 4), ("Quartz", 4), ("Moon Salt", 3), ("Stormglass", 2)),
           area=("harvest_speed", 2),
           note="Sand and salt the grinders keep to themselves, in beds under the works."),
    Secret("mirror-canal-cache", "The Canal Cache", "cache", "drain_grate", None, (2.5, 2.5),
           door_map="mirrorhold_interiors", door_space="cistern_pump_gallery",
           resources=(("Deep Lake Clay", 3), ("Mirror Reed", 3)),
           note="A dry sluice chamber with a chest, a bench and the clay the potters dig from it."),
    Secret("mirror-orrery-vault", "The Orrery Vault", "vault", "cracked_slab", "orrery", (14.0, 6.0), key="Storage Token",
           texts=(("The eleven measures", "Eleven stones, eleven lengths. A shard tuned against all of them is a shard the Barrens factor will sign for."),),
           note="Under the orrery, the keepers' strongroom: the same work counts double here."),
    Secret("mirror-stair-pit", "The East Stair Pit", "pen", "loose_stone", "east-stair", (8.0, 8.0),
           creatures=(("frosthorn_elk", 3), ("crown_antler_stag", 3)),
           note="A quarry pit the stair cut through, where the watch trains against penned elk."),
    Secret("mirror-rose-school", "The Rose Gallery School", "school", "cracked_slab", "rose-gallery", (10.0, -4.0),
           texts=(("Reading", "The gallery's under-room. Books read three times as fast in the quiet."),
                  ("The ringing stone", "The quarry face rings when it is struck and the blank rang clean. Foreman Hesk hung a bell to test it; he does not trust the note."),
                  ("Lenses", "A lens ground here is checked against the mirror basins before it leaves the city.")),
           note="Where the lens-masters teach the apprentices to read a chart before they grind."),
    Secret("mirror-basin-spring", "The Basin Spring", "spring", "loose_stone", "mirror-basins", (-12.0, 6.0),
           note="The warm feed of the mirror basins, in a chamber the masons left open."),
    Secret("mirror-watch-butts", "The South Watch Butts", "range", "cellar_hatch", "south-watch", (6.0, -8.0),
           creatures=(("reedhorn_stag", 3),),
           note="The watch's gallery: straw butts and slow stags at the far end."),
    Secret("mirror-citadel-reliquary", "The Citadel Reliquary", "reliquary", "shrine_slab", "upper-shrine", (8.0, 6.0), key="Mirror Reed",
           texts=(("The citadel", "The citadel was the first lens: a city built to look at one thing."),
                  ("The quarry", "The ringing face is not marble. The blank drawn out of it rang because it was hollow."),
                  ("The bowl", "The range is a bowl with no way out but the cols on its northern rim; the roads that leave, leave by them.")),
           note="The shrine's own relic room, opened with a reed the basins grew."),
    Secret("mirror-cistern-well", "The Cistern Well", "nullwell", "drain_grate", "cistern-yard", (8.0, -8.0),
           creatures=(("riverglass_otter", 4),),
           note="The old cistern: its stones swallow every word of a spell."),
    Secret("mirror-lens-focus", "The Lens Focus", "focus", "crystal_seam", "lens-tower-west", (0.0, 12.0), key="Iron Rune",
           note="Where the west lens tower gathers its light the ether comes cheap."),
    Secret("mirror-adit", "The Quarry Adit", "tunnel", "loose_stone", "quarry-shelf", (-8.0, 10.0),
           resources=(("Quartz", 3), ("Slate", 3)),
           links=(("whitehorn_range", "secret-horn-adit-mouth", "Up into the Whitehorn Range"),),
           note="The quarrymen's adit under the rim, out onto the range."),
    Secret("mirror-waystone", "The Mirror Waystone", "waystone", "cracked_slab", "plaza", (-14.0, 10.0), key="Iron Rune",
           links=(("whitehorn_range_secrets", "horn-waystone", "The Whitehorn Range"),
                  ("amethyst_barrens_secrets", "barrens-waystone", "The Amethyst Barrens"),
                  ("amberwood_secrets", "amber-waystone", "Amberwood"),
                  ("four_gates_secrets", "gates-waystone", "The Four Gates"),
                  ("crownwater_secrets", "crown-waystone", "Crownwater")),
           note="Five stones under the plaza flags. An iron rune wakes them."),
    Secret("mirror-overlook-eyrie", "The Overlook Eyrie", "eyrie", "ivy_arch", "overlook", (8.0, 6.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Crossings", "Every crossing to a neighbouring region has a waygate two tiles inside it, so you see the border before you step over it.")),
           note="A pocket in the overlook cliff with a cistern and a view."),
    Secret("mirror-icebore-mouth", "The Ice-Bore Mouth", "mouth", "ice_crack", "north-post", (-10.0, -8.0),
           links=(("whitehorn_range_secrets", "horn-icebore-far", "Down the ice-bore to the Whitehorn Range"),),
           note="Where the range's ice-bore comes out in Mirrorhold."),
]
