"""Westhaven's secrets: what the harbour city keeps under its quays."""
from secretrooms import Secret

REGION = "westhaven"
NAME = "Westhaven Secrets"
PALETTE = {"floor": "cobble_paving", "wall": "rubble_stone", "ceil": "timber_grey", "rock": "cliff_rock",
           "stone": "ashlar", "timber": "timber_grey", "water": "water_sea", "crystal": "blue_crystal",
           "node": "amber_resin", "turf": "shore_shingle"}
PROP_PALETTE = {"rock": "cliff_rock", "bark": "bark_dark", "stone": "ashlar", "timber": "timber_grey", "dark": "bark_dark"}

SECRETS = [
    Secret("haven-wrack-hollow", "The Wrack Hollow", "grotto", "tide_cave", "gullstone-watch", (10.0, 8.0),
           resources=(("Tidewrack Kelp", 5), ("Shorebank Shell", 4)),
           note="A sea cave under the watch where the wrack piles and the shells are whole."),
    Secret("haven-ropewalk-garden", "The Ropewalk Garden", "garden", "cellar_hatch", "ropewalk", (8.0, 8.0),
           resources=(("Riverflax", 4), ("Cotton", 4), ("Flax", 3), ("Verdigris Bloom", 3)),
           area=("harvest_speed", 2),
           note="Flax and cotton in beds under the ropewalk, where the ropemakers grow their own."),
    Secret("haven-bonded-cache", "The Bonded Cache", "cache", "cellar_hatch", None, (2.0, 2.0),
           door_map="westhaven_insides", door_space="bonded_vaults.bay_b",
           resources=(("Iron Ore", 3), ("Verdigris Bloom", 3)),
           note="A warehouse cellar off the bonded vaults: chest, bench, and ore the customs never weighed."),
    Secret("haven-guild-vault", "The Guild Vault", "vault", "cracked_slab", "guild-hall", (8.0, 8.0), key="Storage Token",
           texts=(("The house seal", "A countersign is checked against the seal-room book. What is made under the guild hall is entered twice, and counts twice."),),
           note="The guild's strongroom, opened with a stored account's token."),
    Secret("haven-mole-pit", "The Mole Pit", "pen", "drain_grate", "mole-bastion", (8.0, -8.0),
           creatures=(("brambleback_boar", 4), ("moss_horn_ram", 3)),
           note="A casemate under the bastion where the militia pens boar and rams."),
    Secret("haven-arcade-school", "The Arcade School", "school", "cracked_slab", "great-arcade", (10.0, 8.0),
           texts=(("Reading", "The arcade's under-room. Books read three times as fast."),
                  ("The post", "The post came back unopened. The reeve says that is the message."),
                  ("Ferries", "Westhaven's berths: one to Crownwater, one to Amberwood. The crossing is a boat, not a road.")),
           note="Where the customs clerks learn their hands."),
    Secret("haven-lamp-spring", "The Lamp Rock Spring", "spring", "loose_stone", "mole-bastion", (-12.0, 12.0),
           note="A warm seep under the light's rock, reached from the landward foot of the mole; "
                "the keepers bathe there."),
    Secret("haven-shipyard-butts", "The Shipyard Butts", "range", "cellar_hatch", "shipyard", (-8.0, 8.0),
           creatures=(("bronze_tide_crab", 3),),
           note="A long shed under the slips with butts and crabs at the far end."),
    Secret("haven-cathedral-reliquary", "The Cathedral Reliquary", "reliquary", "shrine_slab", "cathedral", (10.0, 8.0), key="Shorebank Shell",
           texts=(("The seal", "The false countersign was chalked. The chalk washed off. The seal did not."),
                  ("The escrow", "Someone probed the escrow with a returned letter. It was never opened, and it never needed to be."),
                  ("The wreck", "The wreck assessor's book lists a hull that never sailed.")),
           note="The cathedral's relic room, opened with a shell."),
    Secret("haven-gate-well", "The City Gate Well", "nullwell", "drain_grate", "city-gate", (10.0, 8.0),
           creatures=(("moss_horn_ram", 3),),
           note="The gate's old cistern swallows spells; the rams penned there are honest work."),
    Secret("haven-spire-focus", "The Spire Focus", "focus", "cracked_slab", "high-spire", (8.0, 8.0), key="Iron Rune",
           note="Under the high spire the ether pools; spells cost half."),
    Secret("haven-smuggle", "The Smugglers' Run", "tunnel", "tide_cave", "sea-arch", (10.0, -8.0),
           resources=(("Shorebank Shell", 3), ("Tidewrack Kelp", 3)),
           links=(("amberwood", "secret-amber-smuggle-mouth", "Up into Amberwood"),),
           note="The smugglers' run under the strait, out by Amberwood's harbour."),
    Secret("haven-waystone", "The Haven Waystone", "waystone", "cracked_slab", "fish-market", (8.0, 8.0), key="Iron Rune",
           links=(("grey_moors_secrets", "moor-waystone", "The Grey Moors"),
                  ("manymouth_delta_secrets", "delta-waystone", "The Manymouth Delta"),
                  ("crownwater_secrets", "crown-waystone", "Crownwater"),
                  ("amberwood_secrets", "amber-waystone", "Amberwood")),
           note="Four stones under the fish market. An iron rune wakes them."),
    Secret("haven-lighthouse-eyrie", "The Lighthouse Eyrie", "eyrie", "ivy_arch", "great-lighthouse", (-8.0, 8.0),
           texts=(("Breath", "Rest here and the breath comes back twice as fast."),
                  ("Trade", "The customs house weighs what walks and what rolls. A third added to a wagon on an island that sells bread and rope is not rope.")),
           note="A pocket in the lighthouse footing over the sea."),
    Secret("haven-peatcut-mouth", "The Peat-Cut Mouth", "mouth", "cellar_hatch", "upland-farm", (10.0, 8.0),
           links=(("grey_moors_secrets", "moor-peatcut-far", "Down the peat-cut to the Grey Moors"),),
           note="Where the moors' peat-cut comes up in Westhaven."),
]
